tachiyomiorg/tachiyomi

- app/src/main/res/values/strings.xml
Updated strings to use better-suited words and modified a few that didn't sound right.
> Fix some grammatical issues

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.java
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.java
When navigating to the previous chapter load the last page instead of the first
> Load the last page when switching to the previous chapter

- app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersPresenter.java
Save the sort order for a manga in the sqlite manga table
> save per-manga sort order

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoFragment.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoPresenter.java
- app/src/main/res/layout/fragment_manga_info.xml
- app/src/main/res/values/strings.xml
> Show manga source in info panel

- app/src/main/java/eu/kanade/tachiyomi/data/cache/ChapterCache.java
- app/src/main/java/eu/kanade/tachiyomi/data/cache/CoverCache.java
- app/src/main/java/eu/kanade/tachiyomi/data/cache/CoverGlideModule.java
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryHolder.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoFragment.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoPresenter.java
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedFragment.java
Fixed some mistakes.
Code optimization. Added comments. Few comment mistake fixes
Few comments
Added classes because of renaming
Fixed refactor mistakes :(.
typo + removed todo empty class
Changed o to 0. Some renaming.  Checked for nullability on string.isEmpty() function to prevent crashes
Removed redundant null check
Update ChapterCache.java
Another o to 0 change. Damn this .o! :)
> Code optimization. Added javadoc. Removed setSize for it is not used

- app/build.gradle
- app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.java
Added icons to navigation drawer. Moved settings to the bottom of nav drawer.
> Added icons to navigation drawer #47

- app/src/main/res/values/strings.xml
Fixed grammar issues and reworded some strings for clarity
> Changed the wording on some strings

- app/build.gradle
- app/src/main/java/eu/kanade/tachiyomi/data/cache/CoverCache.java
- app/src/main/java/eu/kanade/tachiyomi/injection/component/AppComponent.java
- app/src/main/java/eu/kanade/tachiyomi/io/IOHandler.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoFragment.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoPresenter.java
- app/src/main/res/layout/fragment_manga_info.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- Removed FAB library now uses the internal one. 
- Changed getTimestamp to modification date.
- Rewrote IOHandler.  
- Fixed Google Drive bug. 
- Tested working for API 16 and 23
- Fixed merge bugs
> Can now manually set cover pictures. #79

- app/src/main/java/eu/kanade/tachiyomi/data/cache/CoverCache.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoFragment.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoPresenter.java
Small fix. Now takes cover from network if anything went wrong while selecting local file. 
Also loadFromCache is private once again!
> Small fix for local cover loading

- app/build.gradle
- app/src/main/java/eu/kanade/tachiyomi/App.java
- app/src/main/java/eu/kanade/tachiyomi/data/rest/GithubService.java
- app/src/main/java/eu/kanade/tachiyomi/data/rest/Release.java
- app/src/main/java/eu/kanade/tachiyomi/data/rest/ServiceFactory.java
- app/src/main/java/eu/kanade/tachiyomi/data/updater/UpdateChecker.java
- app/src/main/java/eu/kanade/tachiyomi/data/updater/UpdateDownloader.java
- app/src/main/java/eu/kanade/tachiyomi/injection/component/AppComponent.java
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAboutFragment.java
- app/src/main/res/values/strings.xml
Code that checks for update when version in settings > about is clicked
> Download updates

- app/src/main/java/eu/kanade/tachiyomi/data/source/base/Source.java
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Batoto.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersFragment.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersPresenter.java
Chapters failing to load is likely caused by batoto removing the content and it's useful to know when that's the case
> Show batoto staff notice if updating chapters failed

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangafox.java
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangahere.java
Batoto already sorts by views and kissmanga doesn't seem to have any way to sort their search results from what I could find.
> sort by views for mangafox and mangahere search results

- app/src/main/java/eu/kanade/tachiyomi/util/ChapterRecognition.java
- app/src/test/java/eu/kanade/tachiyomi/ChapterRecognitionTest.java
> Fix infinite loop when no chapter number is parsed

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoFragment.java
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoPresenter.java
> Improved comments

- app/src/main/java/eu/kanade/tachiyomi/util/ChapterRecognition.java
- app/src/test/java/eu/kanade/tachiyomi/ChapterRecognitionTest.java
#151 fixed the recursion, this fixes the parse failures from #147
> Chapter recognition improvements

- README.md
> Fix link broken by PR #164

- README.md
> Add link to wiki about debug F-Droid

- app/src/main/java/eu/kanade/tachiyomi/data/source/SourceManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Mangachan.java
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Mintmanga.java
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Readmanga.java
Add parsers for 
http://readmanga.me/
http://mintmanga.com/
http://mangachan.ru/
> Implement parsers for Readmanga, Mintmanga and Mangachan

- app/src/main/java/eu/kanade/tachiyomi/data/source/SourceManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/ReadMangaToday.java
Hello !
I quickly added a new parser for the website : http://readmanga.today/ 
I did it because it is the only site that's not blocked on my network. 
Ask me if I have anything to change !
> Implement parser for readmanga.today

- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/util/ViewExtensions.kt
- app/src/main/java/eu/kanade/tachiyomi/widget/RevealAnimationView.kt
- app/src/main/res/drawable/ic_sort_by_alpha_white_24dp.xml
- app/src/main/res/layout/fragment_manga_chapters.xml
- app/src/main/res/layout/item_chapter.xml
- app/src/main/res/menu/chapters.xml
- app/src/main/res/values/strings.xml
> Updated manga chapters UI

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/RecentChaptersFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/RecentChaptersHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/RecentChaptersPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsDownloadsFragment.kt
- app/src/main/res/values/keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_downloads.xml
> Fix Issue #42

- app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/serializer/IdExclusion.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/serializer/IntegerSerializer.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/DatabaseHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/RawQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/Category.java
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.java
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/MangaSync.java
- app/src/main/java/eu/kanade/tachiyomi/injection/component/AppComponent.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/backup/BackupFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/backup/BackupPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
- app/src/main/res/drawable/ic_backup_black_24dp.xml
- app/src/main/res/layout/fragment_backup.xml
- app/src/main/res/menu/menu_navigation.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/eu/kanade/tachiyomi/BackupTest.java
This PR implements #34.
The backend is already done, it's missing a proper UI (dialog to save, restore, etc...)
Suggestions are welcome.
> Support backups

- .travis.yml
- README.md
- gradle.properties
- libs/SubsamplingScaleImageView/build.gradle
Fix travis builds and rearrange badges on readme
> Travis builds

- app/build.gradle
`./gradlew clean assembleDebug -PversionCode=<code>`
> Allow setting versionCode in parameter

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Batoto.java
- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseRxActivity.java
- app/src/main/java/eu/kanade/tachiyomi/ui/base/adapter/SmartFragmentStatePagerAdapter.java
- app/src/main/java/eu/kanade/tachiyomi/ui/base/decoration/DividerItemDecoration.java
- app/src/main/java/eu/kanade/tachiyomi/ui/base/fragment/BaseRxFragment.java
- app/src/main/java/eu/kanade/tachiyomi/widget/EndlessGridScrollListener.java
- app/src/main/java/eu/kanade/tachiyomi/widget/EndlessListScrollListener.java
- app/src/main/java/eu/kanade/tachiyomi/widget/EndlessScrollListener.java
This pull request is focused on resolving occurrences of Sonar rule pmd:ImmutableField - Immutable Field
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:ImmutableField
M-Ezzat
> pmd:ImmutableField - Immutable Field

- app/src/main/java/eu/kanade/tachiyomi/Constants.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadNotifier.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/UpdateDownloader.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadPresenter.kt
- app/src/main/res/values/strings.xml
> Chapter download notification

- app/src/main/java/eu/kanade/tachiyomi/ui/recent/RecentChaptersFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/RecentChaptersHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/RecentChaptersPresenter.kt
- app/src/main/res/layout/fragment_recent_chapters.xml
- app/src/main/res/layout/item_recent_chapter.xml
- app/src/main/res/menu/chapter_recent_selection.xml
> Added improvements for RecentChapters. Closes #320

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Readmanga.kt
Old regex can't read all the variants links to pages
> Improve regex for pages from Readmanga and Mintmanga

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Mangachan.kt
Mangachan has been updated and moved to other domain.
After that covers isn't loading.
> Update Mangachan address and fix loading covers after update

- app/src/main/java/eu/kanade/tachiyomi/data/source/SourceManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/OnlineSource.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangasee.kt
As batoto is sometimes removing scanlations there is a need for comparable quality scans.
> Mangasee as image source

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Readmangatoday.kt
ReadManga Today started using Cloudflare resulting in a lot of 520s.
> Use Cloudflare client for ReadManga.Today

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_general.xml
Added in the startup screen option requested in #348
Closes #348
> Added a startup screen preference option

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Readmanga.kt
Implementation genre filter for readmanga.me and mintmanga.com
Mangachan doesn't have search by genre
> Implement genre filter for Readmanga and Mintmanga

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangahere.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangasee.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Readmangatoday.kt
Adds genre filter support for mangahere, mangasee and readmangatoday
> Add genre filter support for the remaining English sources

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
- app/src/main/res/menu/chapters.xml
- app/src/main/res/raw/changelog_debug.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_downloads.xml
- Added read filter to chapter select.
- Can now select how far back the chapter should be deleted after read.
Closes #390
> Added read filter to chapter select.

- app/.gitignore
- app/build.gradle
Allows users to have custom Gradle settings
> Gradle custom.propetries

- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadNotifier.kt
> Download queue will now be reset if negative.

- app/src/main/res/values-pt/strings.xml
-New strings required translation
-Correcting mistakes
> Update Portuguese(pt_PT) translation.

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Readmangatoday.kt
Everything is in the title :smile:
> Added support for latest updates to Readmangatoday

- app/src/main/java/eu/kanade/tachiyomi/data/database/DbOpenHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/mappers/ChapterTypeMapping.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/Chapter.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/ChapterImpl.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/ChapterProgressPutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/tables/ChapterTable.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersPresenter.kt
- app/src/main/res/layout/item_chapter.xml
- app/src/main/res/menu/chapter_single.xml
- app/src/main/res/menu/chapters.xml
- app/src/main/res/values/strings.xml
Closes #89 
Multi-select isn't enabled for bookmark because I think it gets too crowded, and it's not really necessary for the bookmark use case.
> Added option to bookmark single chapter

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangasee.kt
Possibly Closes (https://github.com/inorichi/tachiyomi/issues/516)
> Update MangaSee URL

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangasee.kt
Update for Mangasee source due to webpage changes.
From my understanding there is no way to update existing mangas added to library and you have to remove and readd them one by one.
> Update Mangasee due to webpage changes

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangasee.kt
With the new layout mangas that Mangasee considers having seasons are broken.
> Update for seasonal manga from Mangasee

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Mangachan.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Readmanga.kt
* Implemented genre filter for Mangachan
* Fixed search for Mangachan
* Changed url with latest updates for Mangachan
* Updated genres for Readmanga
* Removed duplicate code for Readmanga
>  Some improvements for russian catalogs

- app/src/main/res/values-it/strings.xml
I have translated the strings.xml in Italian.
I had doubts about some decisions (such as whether/how to translate Download), I would appreciate if someone else would give a look.
> Italian language

- app/src/main/java/eu/kanade/tachiyomi/Constants.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/CatalogueFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryFragment.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryNavigationView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySort.kt
- app/src/main/java/eu/kanade/tachiyomi/widget/ExtendedNavigationView.kt
- app/src/main/res/drawable/empty_drawable_32dp.xml
- app/src/main/res/drawable/ic_keyboard_arrow_down_black_32dp.xml
- app/src/main/res/drawable/ic_keyboard_arrow_up_black_32dp.xml
- app/src/main/res/layout/library_drawer.xml
- app/src/main/res/layout/navigation_view_checkbox.xml
- app/src/main/res/layout/navigation_view_checkedtext.xml
- app/src/main/res/layout/navigation_view_radio.xml
- app/src/main/res/menu/library.xml
- app/src/main/res/values/strings.xml
- build.gradle
I'm not sure how to indicate an active filter. The two options I can think of are:
* ~~Reduce icon's alpha (easy).~~
* ~~Add a custom icon with a dot at the top right edge (harder).~~
Instead of the two other options, the icon is tinted yellow when there's a filter active.
> Add drawer to filter and sort the library

- app/src/main/java/eu/kanade/tachiyomi/data/updater/UpdateDownloaderService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/UpdateNotificationReceiver.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/notification/ImageNotificationReceiver.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/notification/ImageNotifier.kt
- app/src/main/res/xml/provider_paths.xml
> Fixed updater on Android N.

- app/src/main/java/eu/kanade/tachiyomi/ui/recent_updates/RecentChaptersFragment.kt
- app/src/main/res/layout/fragment_recent_chapters.xml
Solves #550
Note: I assume that the library update operation automatically updates the library updates list - but I have no reliable method of testing this atm as I have no idea what manga will come out tommorow
> Refresh option in the library updates tab

- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Batoto.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Kissmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangafox.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangahere.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangasee.kt
- app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Readmangatoday.kt
- add a "Compled" filter to all english sources;
- fix Mangahere manga title extraction (search);
- fix Mangafox search (#603).
> Add "Completed" filter; fix Mangahere; fix Mangafox

- app/src/main/res/values-it/strings.xml
Super small PR to fix the typo mentioned in #629
> Fixed a typo in an Italian string (#629)

- app/src/main/res/values-v21/keys.xml
- app/src/main/res/values/keys.xml
Very minor PR: added translatable="false" to keys so that they aren't shown as untranslated in strings editor (useful when someone wants to know which strings still need a translation)
> Added translatable="false" to keys

- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mangachan.kt
I'm sorry for fix this so late. Exams
> Fix Mangachan issue from #628

- app/src/main/res/values-vi/strings.xml
Stupid mistake. Last time I'm commiting via github ;)
> Language hot fix

- app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
Small PR to solves issue #665 (from the end user prospective).
Chapter with the same (recognized) chapter number are now sorted by chapter name (from the file name). In this way even when chapter numbers are missing the chapter order is not random.
> Improve local manga chapter sorting

- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Readmanga.kt
@inorichi can i open PR to this repo or i need open PR to tachiyomi-extensions repo?
> Chapter Recognition for Read/Mintmanga

- app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsDownloadsFragment.kt
- app/src/main/res/values/keys.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/pref_downloads.xml
Closes #700 
Added option to select which categories use auto download function.
> Category-specific auto download

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonReader.kt
> Retain last read page when using the webtoon mode

- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/ActivityMixin.kt
- app/src/main/res/drawable-v21/library_item_selector_amoled.xml
- app/src/main/res/drawable-v21/list_item_selector_amoled.xml
- app/src/main/res/drawable/library_item_selector_amoled.xml
- app/src/main/res/drawable/list_item_selector_amoled.xml
- app/src/main/res/layout/fragment_recently_read.xml
- app/src/main/res/layout/item_recently_read.xml
- app/src/main/res/values-v21/themes.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/themes.xml
> Initial AMOLED theme + some CardView fixes

- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
- app/src/main/res/layout/fragment_recently_read.xml
- app/src/main/res/layout/fragment_track.xml
- app/src/main/res/layout/item_recently_read.xml
- app/src/main/res/layout/item_track.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
> Fixed tracking cardview + readded AMOLED theme.

- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/ChapterQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/MangaQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/RawQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryNavigationView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySort.kt
- app/src/main/res/values/strings.xml
> allow sorting by total chapters for library view

- app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> Simultaneous download will now show on start.

- app/src/main/java/eu/kanade/tachiyomi/util/ChapterRecognition.kt
- app/src/test/java/eu/kanade/tachiyomi/data/database/ChapterRecognitionTest.kt
> Fixes case where manga name ends with s.

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryNavigationView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
- app/src/main/res/values/strings.xml
> Add Filter by Completed for library

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- README.md
Revise the way users are directed when coming to report a problem or request a feature.
Closes #944 
Suggestions welcome, waiting for reviews.
> README, CONTRIBUTING and ISSUE_TEMPLATE, Discord

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChapterHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent_updates/RecentChapterHolder.kt
- app/src/main/res/layout/recent_chapters_item.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
> 	Fix tint on AMOLED theme

- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Readmanga.kt
Also update genres and some codestyle changes
> Fix search on readmanga/mintmanga

- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryNavigationView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySort.kt
> Add option to sort library by source.

- app/src/main/java/eu/kanade/tachiyomi/source/online/english/Mangahere.kt
> Fix downloads from mangahere

- app/src/main/AndroidManifest.xml
- app/src/main/java/eu/kanade/tachiyomi/data/notification/NotificationReceiver.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoController.kt
- app/src/main/res/values/strings.xml
> Shortcut fix Oreo

- app/src/main/java/eu/kanade/tachiyomi/source/online/english/Mangahere.kt
addresses #1030.
Manga here changed internal urls from http://www to just //www
> fixed author/artist not showing for Mangahere.

- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mangachan.kt
- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Readmanga.kt
> Fix covers url on Mangachan.

- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-bg/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-id/strings.xml
- app/src/main/res/values-ms/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru/strings.xml
Continuing the #881 PR.
More information: https://github.com/inorichi/tachiyomi/wiki/Translation
**Comment for translator access and new languages.**
Current status:
[![Translation status](http://weblate.j2ghz.com/widgets/tachiyomi/-/multi-auto.svg)](http://weblate.j2ghz.com/engage/tachiyomi/?utm_source=widget)
> Translations

- app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupRestoreService.kt
- app/src/main/res/values-de/strings.xml
> Restore tracking on backup

- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Readmanga.kt
After last updates on this sites first field can be empty
> Update regexp for pages from Readmanga/Mintmanga

- app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryController.kt
- app/src/main/res/drawable/ic_shape_black_128dp.xml
- app/src/main/res/layout/categories_controller.xml
- app/src/main/res/layout/common_view_empty.xml
- app/src/main/res/layout/library_controller.xml
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values/strings.xml
Small new user improvements
- Changed empty library string
- Added empty view for Categories
> Small new user improvements

- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mangachan.kt
Added support for russian sources mangachan.me: Group by and status
@Taumer can you review please?
> Mangachan advanced support

- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Readmanga.kt
Servers with pics now check Referer
> Add referer to readmanga/mintmanga requests header

- app/src/main/java/eu/kanade/tachiyomi/source/online/english/Readmangatoday.kt
> fixed ReadMangaToday search issue

- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/global_search/CatalogueSearchCardHolder.kt
> Alpha fix for Global Search

- app/build.gradle
- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCatalogueController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/CatalogueNavigationView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/filter/GroupItem.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/filter/SortGroup.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/filter/SortItem.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryController.kt
- app/src/main/res/drawable/ic_arrow_down_32dp.xml
- app/src/main/res/drawable/ic_arrow_up_32dp.xml
- app/src/main/res/layout/catalogue_drawer_content.xml
- app/src/main/res/values/strings.xml
I think everything was addressed for #1155  
Made drawer swipe to open/close
moved search/reset to bottom and swapped positioning
fix collapse bug
click search closes drawer
switched to arrow for sort
| ![](https://user-images.githubusercontent.com/2092019/34737757-07ce62a8-f545-11e7-9027-d5b4ddaf2949.png)| ![](https://user-images.githubusercontent.com/2092019/34737767-12b93102-f545-11e7-8e2f-7b1a8cee4a7a.png) |
|:---:|:---:|
> Catalog visuals update 1155

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/DownloadChaptersDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/DownloadCustomChaptersDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/widget/DialogCustomDownloadView.kt
- app/src/main/res/drawable/ic_chevron_left_black_24dp.xml
- app/src/main/res/drawable/ic_chevron_left_double_black_24dp.xml
- app/src/main/res/drawable/ic_chevron_right_black_24dp.xml
- app/src/main/res/drawable/ic_chevron_right_double_black_24dp.xml
- app/src/main/res/layout/download_custom_amount.xml
- app/src/main/res/layout/navigation_download_chooser.xml
- app/src/main/res/values/strings.xml
Because there aren't enough pull request yet.
The extra option looks bloated though. So thinking about removing one of the options, not sure which one.
> Added custom download option

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChapterHolder.kt
didn't realize it was dynamically setting also
> fixed chapter  3 dot icon

- app/src/main/java/eu/kanade/tachiyomi/source/online/english/Readmangatoday.kt
fix genre tags to be delimited correctly
> ReadMangaToday genre tag fix

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
> Add page down/page up hardware detection

- app/src/main/java/eu/kanade/tachiyomi/data/database/DbOpenHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/mappers/TrackTypeMapping.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/Track.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/TrackSearch.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/tables/TrackTable.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/TrackService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistModels.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/Kitsu.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuApi.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuModels.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/model/TrackSearch.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeList.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyanimelistApi.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackAdapter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSearchAdapter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSearchDialog.kt
- app/src/main/res/layout/track_item.xml
- app/src/main/res/layout/track_search_dialog.xml
- app/src/main/res/layout/track_search_item.xml
- app/src/main/res/values/strings.xml
Addresses #1158 
Also added click to logo to launch the tracking websites url for the manga
Needs some minor ui adjustments as well as contemplating click to show all of summary?
> Improve tracking search results

- app/src/main/java/eu/kanade/tachiyomi/util/ChapterSourceSync.kt
change chapter update to refresh on any metadata change
namely the two missing were date uploaded and chapter number
> Chapter Metadata update

- app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/serializer/TrackTypeAdapter.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/TrackImpl.kt
addresses #1265.
Fixes restores from old backup into new updated trackimpl with tracking url.
adds tracking url to backup like i should have done originally @NoodleMage  😄
> fix restore from old backup to updated trackimpl.

- app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistModels.kt
fixes issue where some anilist results not showing due to null description causing a null pointer
> Anilist search fix

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersController.kt
I'm not actually 100% sure if this works because I've never programmed in kotlin before, but unless there's some property I'm missing, it should be fine. 😄
> Fixed marked previous as read not deleting chapters

- app/src/main/res/layout-land/manga_info_controller.xml
- app/src/main/res/layout/manga_info_controller.xml
Addresses issues related to pr #1139 as well as some other minor tweaks.
Todo:
> Fixes and Tweaks to Info Page

- app/src/main/res/values-v21/themes.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
> Dialog color fix

- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mangachan.kt
- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Readmanga.kt
1) moved headerBuilder to imageRequest
2) changed the method of gets thumbnails
3) updated js for genres
4) update genre list
> Update russian sources

- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAboutController.kt
Adds link to github in the About page of settings.
> Added Github link to about.

- .github/CONTRIBUTING.md
- README.md
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAboutController.kt
Please check if I didn't forget any link
> Vanity url

- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Readmanga.kt
> Update date selector and chapter number recognition for readmanga/mintmanga

- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuApi.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuModels.kt
Was recommend by Kitsu Dev team.
This fixes  issue where a newly added manga to kitsu doesnt show in normal api search.
> Changed Kitsu to use Algoria search directly

- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuModels.kt
fixed filtering of novel, fixed start date not showing
> Kitsu search fix

- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuApi.kt
> Fix NSFW Manga not showing in Kitsu

- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Mintmanga.kt
- app/src/main/java/eu/kanade/tachiyomi/source/online/russian/Readmanga.kt
On the `Latest updates` page sometimes manga appears without cover
> Fix potential NPE at cover image selector (readmanga/mintmanga)

- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersPresenter.kt
> Filter local manga as downloaded

- core-android/build.gradle
- ui/src/main/kotlin/ui/base/ControllerTransitions.kt
- ui/src/main/kotlin/ui/base/SimpleTransitionChangeHandler.java
- ui/src/main/res/layout/catalogbrowse_filters_sheet.xml
- ui/src/main/res/layout/catalogs_card_item.xml
- ui/src/main/res/layout/filter_group.xml
- ui/src/main/res/layout/manga_grid_item.xml
- ui/src/main/res/layout/manga_header_item.xml
- ui/src/main/res/layout/manga_list_item.xml
- ui/src/main/res/values/styles.xml
- ui/src/main/res/values/themes.xml
Filter dialog has finally joined the dark side....
> Implemented new Material fonts styeles. Fixed bottomDialog color

- app/src/main/java/eu/kanade/tachiyomi/network/CloudflareInterceptor.kt
From Anorov/cloudflare-scrape#193
Related issues: inorichi/tachiyomi-extensions#894
~~This PR has Line Ending changes. Sorry. (That's why i spammed force push)~~
Turned off AutoCRLF xD
> [Cloudflare] Fix SyntaxError due to recent js challenge changes.

- README.md
Seems F-Droid is not updated anymore.
Please close this issue if it doesn't
PS. I just opened this PR because I saw some users who uses F-Droid build...
> Remove F-Droid on README.md

- app/src/main/java/eu/kanade/tachiyomi/network/CloudflareInterceptor.kt
Related issues: inorichi/tachiyomi-extensions#951
From: Anorov/cloudflare-scrape#200
> [Cloudflare] Fix 503 due to missing value in js challenge.

- app/src/main/java/eu/kanade/tachiyomi/network/CloudflareInterceptor.kt
From Anorov/cloudflare-scrape#206
Related issues: inorichi/tachiyomi-extensions#951
Recent CF changes research: https://github.com/inorichi/tachiyomi-extensions/issues/951#issuecomment-475467259
Ps. [`atob` package in NPM reaches ~780K downloads/week](https://www.npmjs.com/package/atob)
> [Cloudflare] Fix recent CF JS Challenge error that calls DOM

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt
- app/src/main/res/values/strings.xml
fixes #988   
Gives option to skip read.  The extra logic in readerPresenter allows a read chapter to be selected initially.
> add option to skip chapters marked read

- source-api/src/main/java/tachiyomi/source/model/MangaInfo.kt
add publishing finished status for sources that indicate this but the manga is not completed.
> 1.x - add new manga status

- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
> Ignore case while sorting Library

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> Update tracking sites after finishing chapter

- app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
- app/src/main/res/menu/menu_navigation.xml
- app/src/main/res/values/strings.xml
> Add help link to nav drawer

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoController.kt
> Long click to manage categories

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoController.kt
> Fix the category selection bug

- app/src/main/java/eu/kanade/tachiyomi/data/updater/GithubUpdateResult.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/Release.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/UpdateChecker.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/UpdateResult.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/UpdaterJob.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/devrepo/DevRepoRelease.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/devrepo/DevRepoUpdateChecker.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/devrepo/DevRepoUpdateResult.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/github/GithubRelease.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/github/GithubService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/github/GithubUpdateChecker.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/github/GithubUpdateResult.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAboutController.kt
> Add automatic updates for dev builds

- README.md
Wiki has been replaced by website.
> Update link in FAQ

- app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionGroupHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionGroupItem.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionPresenter.kt
Makes it slightly easier to read through. We may want to moved installed/available into different tabs too.
Partial screenshot: https://imgur.com/0mDRVhq
> Group available extensions by language

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerTransitionHolder.kt
Requested in this issue #2264.
> Increase default text size of the transition chapter page

- .travis.yml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCatalogueController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAboutController.kt
Intermediate step to get to SDK 29/AndroidX...
> Update to SDK 28

- app/build.gradle
- app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/DirectoryPageLoader.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/RarPageLoader.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/ZipPageLoader.kt
- app/src/main/java/eu/kanade/tachiyomi/util/ComparatorUtil.kt
Don't really see the need for an extra dependency for this.
> Replace dependency for case insensitive natural sorting

- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCatalogueController.kt
https://github.com/inorichi/tachiyomi/issues/2401
This should do the trick.
Recycler view should not be fixed size.
> Issue #2401 Catalogue List View

- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCatalogueController.kt
Fixes #2409  in a more performance minded way
@arkon  After you mentioned potential performance issues.  I realized the issue was for listview there it does not match parent for width and height like the grid view (catalogue_recycler_autofit) does
> add width and height to listview for browseCatalogueController

- app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeList.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeListInterceptor.kt
MAL API waiting room 💀
MAL has a known issue where it invalidates any login sessions if they are inactive for a couple of days.
Auto attempt a login refresh if MAL returns a 400 indicating the login is no longer valid.
> MAL Tracking Improvements

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonTransitionHolder.kt
> match transition text used by other readers

- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt
- app/src/main/res/layout/chapters_controller.xml
- app/src/main/res/layout/library_category.xml
Based roughly on https://github.com/Jays2Kings/tachiyomiJ2K/commit/d8f385cc636da9cc56cf52ad7e8d2c142f577ca6 , but I don't see the need for the bubble (especially if contents aren't sorted alphabetically).
> Add fast scroller to library

- app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
Simple loading of metadata from a JSON file for local manga. Implement issue #698.
> JSON metadata for local manga

- app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/BaseController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCatalogueController.kt
Fixes https://github.com/inorichi/tachiyomi/issues/2358
> Fix catalogue search focus automatically being removed

- app/src/main/java/eu/kanade/tachiyomi/extension/ExtensionManager.kt
- app/src/main/java/eu/kanade/tachiyomi/extension/model/Extension.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionDetailsController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionPresenter.kt
- app/src/main/res/drawable/button_bg_error.xml
- app/src/main/res/layout/extension_detail_controller.xml
- app/src/main/res/values/strings.xml
> Indicate obsolete extensions

- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryItem.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoController.kt
Using the search bar in My Library, you can search tags for manga (ie. "Romance") or exclude (ie. "-Comedy") You can also search multiple by seperating by commas (ie. "Romance, -Comedy")
Clicking the tag in manga info from the library also performs a local serach
> Local genre tag searching

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
Fixes #2113
I'm not entirely sure why it was doing what it was doing before. Am I missing something?
> Directly pass read chapter when updating tracker

- app/src/main/java/eu/kanade/tachiyomi/network/AndroidCookieJar.kt
- app/src/main/java/eu/kanade/tachiyomi/network/CloudflareInterceptor.kt
The idea here is that instead of checking the URL to see if Cloudflare has been successfully bypassed, instead we check if we have the "cf_clearance" cookie that's set when Cloudflare is bypassed.
> CloudflareInterceptor update

- app/src/main/res/values-fr/strings.xml
> Fix a string formatter

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> Bug #2548 fix NPE in dateFormat pref

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderSettingsSheet.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt
- app/src/main/res/layout/reader_settings_sheet.xml
- app/src/main/res/values/strings.xml
- Notch device support fullscreen 
- Make fullscreen switching smoother
> Fix fullscreen reader for notch device

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
- app/src/main/res/values/strings.xml
> Support follow system theme[Android 10]

- app/src/main/java/eu/kanade/tachiyomi/network/CloudflareInterceptor.kt
Avoid User-Agent mismatch between WebView and OkHttp when User-Agent is Empty, see https://developer.android.com/reference/android/webkit/WebSettings#setUserAgentString(java.lang.String)
> Fix Cloudflare Interceptor when User-Agent is Empty

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt
As per conversation in https://github.com/inorichi/tachiyomi/pull/2707, made the center style as default and only.
> Changed default pager zoom style to ZOOM_FOCUS_CENTER

- app/src/main/res/values-ca/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-ms/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-sv/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
**Merge just before next release** or when there's a significant amount of translations waiting
Continues from #2679
More information: https://tachiyomi.org/help/contribution/#translation
Current status:
[![Translation status](https://hosted.weblate.org/widgets/tachiyomi/-/multi-auto.svg)](https://hosted.weblate.org/engage/tachiyomi/?utm_source=widget)
> Translations (Continuous)

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderSettingsSheet.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonConfig.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
Add continuous vertical reading mode for people who like the webtoon reader, but want padding between pages, without messing up actual webtoons
> Add Continuous vertical reading mode

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChapterHolder.kt
Now matches bookmark color (accent color)
Preview on default dark/light variants:
> Change color of 'last page read' in chapter description

- app/src/main/java/eu/kanade/tachiyomi/extension/util/ExtensionInstaller.kt
Fixes https://github.com/inorichi/tachiyomi/issues/2107
Honestly I still have no idea what the exact issue is. My best guess is it's the same issue as the one described in the comment block, except it also affects certain devices post N. 
`Due to a bug in Android versions prior to N, the installer can't open files that do not contain the extension in the path, even if you specify the correct MIME.`
Unfortunately since the issue is device dependent, I only have a sample size of one person that confirmed this change works (Android 7.0, vivo 1713)
Also tested on pre and post N emulators without noticing any issues.
> Fixes Issue #2107

- app/build.gradle
- app/proguard-rules.pro
La-dee-dah...♪ realizing nucleus can be updated without any changes needing to be made... don't mind me... ♪
> Update nucleus because we can

- app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeListApi.kt
> Fix MAL api updating wrong data on read chapters change (#2971)

- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadNotifier.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/widget/preference/TrackLogoutDialog.kt
- app/src/main/res/values-hi/strings.xml
~~Fix hindi formatting strings~~ Strings changed on weblate
Prefer `context.getString()` for formatting since android studio is able to detect formatting errors.
Also I'm using this PR to plug an issue with the title of `TrackLogoutDialog`, since `R.string.logout_title` is a format string but is no longer being passed any args.
> String Formatting Fixes

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourcePresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/SourceComfortableGridHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/SourceGridHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/SourceItem.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryComfortableGridHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryGridHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryItem.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
- app/src/main/res/layout/source_comfortable_grid_item.xml
- app/src/main/res/menu/source_browse.xml
- app/src/main/res/values/strings.xml
Add a comfortable grid (grid but with title under the image) setting in the library bottom sheet and as a setting in the switch mode action in browse source
> Comfortable Grid

- app/src/main/java/eu/kanade/tachiyomi/util/MangaExtensions.kt
Handle default category and add favourite check.
> Download new chapters bug fix

- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourcePresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchAdapter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchHolder.kt
Implement the EH more button in a more easy to add manner
> Global Search click title to search in Source

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
closes #3252 
It seems like when attempting to delete previous nth to last chapter it is supposed to check if that chapter was actually downloaded, but instead was checking current chapter.
fix: now retrieves chapter to delete before attempting to enqueue and checks if it has to delete before attempting.
> Chapter nth to the last deletion logic fixed

- app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/BaseController.kt
fix #3422 toolbar menu are hidden when opening dialog
> fixes #3422

- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadService.kt
> fix: Download on WiFi regardless of metered status

- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadCache.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadPendingDeleter.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
I did some testing and it seems to work as expected, I found no issues, the chapters properly read the old and new folder styles, while downloading to the new folder style.
> Change to J2k style downloads while keeping support for the old ones

- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadNotifier.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
- app/src/main/java/eu/kanade/tachiyomi/data/notification/Notifications.kt
- app/src/main/res/values/strings.xml
After seeing the request I think it is a really good feature to have so I made some minor updates to get it running.
Show a download complete notification channel when all downloads are completed. Auto cancels when onclick and navigate to download screen.
Closes #3475
> [Feature Request] - Download Complete Remidner #3475

- app/src/main/res/values/strings.xml
Relates to #3659. If this is not the proper way to update the app strings then please let me know.
> Update and clarify message on tracking services

- app/src/main/res/layout/extension_controller.xml
- app/src/main/res/layout/migration_sources_controller.xml
- app/src/main/res/layout/source_main_controller.xml
closes #3733 
The extension/migrate list had similar problems as the source list
> Add spacing on top of sources/extensions/migrate lists

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/MissingChapters.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ReaderTransitionView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonAdapter.kt
What it does it that it always show chapter transition when there are missing chapters
> Always show missing chapter warning if there are missing chapters

- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/HistoryQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/RawQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryAdapter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryPresenter.kt
- app/src/main/res/menu/history.xml
Added slightly modified infinite history and search history from AZ/SY
Closes #2877
> Add infinite history and search history

- app/src/main/res/layout/reader_color_filter_sheet.xml
Fixes #3860 
Before:
| Blueprint | Preview |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/6576096/94529068-8c968c00-0239-11eb-9534-c1a4b3a22692.png) | ![image](https://user-images.githubusercontent.com/6576096/94529679-50176000-023a-11eb-967d-dcd9b4a86c6d.png) |
After:
| Blueprint | Preview |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/6576096/94529084-928c6d00-0239-11eb-9490-3635be30d457.png) | ![image](https://user-images.githubusercontent.com/6576096/94530093-e2b7ff00-023a-11eb-977e-03ca82083f33.png) |
> Fix color filter sheet content alignment

- app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryPresenter.kt
> Fix deleting history not refreshing the view

- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedController.kt
- app/src/main/res/values/strings.xml
Closes #1799
**What it does**
It adds the ability to delete all reading history with one button
> Ability to delete reading history

- app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupCreateService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupRestoreService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/UpdaterService.kt
- app/src/main/java/eu/kanade/tachiyomi/extension/util/ExtensionInstaller.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/BrowseController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionTrustDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/SourcePreferencesController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/manga/MigrationMangaController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/latest/LatestUpdatesController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/DownloadCustomChaptersDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/SetChapterSettingsDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/SetTrackChaptersDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/SetTrackReadingDatesDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/SetTrackScoreDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/SetTrackStatusDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSearchDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/more/AboutController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsBackupController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/track/TrackLoginDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/track/TrackLogoutDialog.kt
- app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt
- app/src/main/java/eu/kanade/tachiyomi/util/system/LocaleHelper.kt
- buildSrc/src/main/kotlin/Dependencies.kt
Pretty much what the title says.
> Use some more KTX and Compat stuff

- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchHolder.kt
- app/src/main/res/layout/global_search_controller_card.xml
> Replace language code in Global Search with secondary text

- app/src/main/res/values/colors.xml
Changed Default gray colours to Google gray colours
> Tweaked Default theme

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderSettingsSheet.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ViewerConfig.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ViewerNavigation.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/navigation/EdgeNavigation.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/navigation/KindlishNavigation.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/navigation/LNavigation.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerDefaultNavigation.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonConfig.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonDefaultNavigation.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
- app/src/main/java/eu/kanade/tachiyomi/util/lang/RectFExtensions.kt
- app/src/main/res/layout/reader_settings_sheet.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
Closes #2152 
Closes #2361, and closes #3678 with Edge navigation
**What differs from the other PR**
- Default navigation behaves more like current reader navigation
- Adds the ability to invert viewer navigation
- Adds additional Edge navigation
> Viewer navigation

- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
> add date Format

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ViewerNavigation.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/navigation/LNavigation.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerDefaultNavigation.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
Based on feedback from #4237
This fixes navigation issues with L Navigation (Default for Webtoon, Vertical, and Continous Vertical) not matching previous build navigation. And (Right to Left)/(Left to Right) not using moveRight and -Left resulting in needing to invert navigation to match previous build
> Fix navigation from feedback

- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/TrackQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
- app/src/main/res/values/strings.xml
closes #1899
Checks if a manga is tracked and checks if you are logged into that tracking service
https://user-images.githubusercontent.com/6576096/104059037-eae9e800-51f4-11eb-96e5-fd5b7e6645b6.mp4
> Add filter for tracking

- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
- app/src/main/java/eu/kanade/tachiyomi/widget/ExtendedNavigationView.kt
- app/src/main/res/values/strings.xml
closes #4307
Adds `isVisible` attribute to `MultiState` which is then used to make `MultiStateHolder` not visible
https://user-images.githubusercontent.com/6576096/104925531-4491a580-599f-11eb-9978-a52eb250774e.mp4
---
Also changed the logic for checking if a manga is being tracked
From
```kt
return db.getTracks().asRxObservable().map { tracks ->
tracks.associate { track ->
// Checks if any tracker is logged in for any manga being tracked
val isLogged = tracks.any { trackManager.getService(it.sync_id)?.isLogged ?: false }
// Manga id will always be true if one tracker is logged, a manga 
// can use another tracker that is not logged in and still show up
Pair(track.manga_id, isLogged) 
}
}
```
| Result (Only MAL is logged in) |  |
|---|---|
| …
> Hide tracking when no tracker is logged in and change filter logic

- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt
> Fix multi-select phantom anchor bug in manga chapters and library

- app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadHolder.kt
- app/src/main/res/layout/download_item.xml
> add source name in download queue

- app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadController.kt
- app/src/main/res/menu/download_queue.xml
- app/src/main/res/values/strings.xml
<table>
<tr>
<th>sort by smallest</th>
<th>sort by biggest</th>
</tr> 
<tr>
<td><img src="https://user-images.githubusercontent.com/16263232/105580214-a302bd80-5dbd-11eb-8ae1-7dcf29bcce3d.png" alt=""></td>
<td><img src="https://user-images.githubusercontent.com/16263232/105580225-ab5af880-5dbd-11eb-9409-73f454d619e7.png" alt=""></td>
</tr>
</table>
> add sort by chapter number in download queue

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
- app/src/main/res/values/strings.xml
| No logged in tracker | One logged in tracker | Multiple logged in trackers |
|---|---|---|
| ![Screenshot_1611482424](https://user-images.githubusercontent.com/6576096/105626894-6bcef380-5e33-11eb-94eb-85a2cd839245.png) | ![Screenshot_1611482412](https://user-images.githubusercontent.com/6576096/105626896-6ec9e400-5e33-11eb-9842-d04f3c760973.png) | ![Screenshot_1611482391](https://user-images.githubusercontent.com/6576096/105626910-843f0e00-5e33-11eb-853b-f5b97d276eb7.png) |
> Extend track filter

- app/build.gradle.kts
- app/src/main/java/eu/kanade/tachiyomi/data/database/mappers/CategoryTypeMapping.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/mappers/ChapterTypeMapping.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/mappers/HistoryTypeMapping.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/mappers/MangaCategoryTypeMapping.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/mappers/MangaTypeMapping.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/mappers/TrackTypeMapping.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/ChapterBackupPutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/ChapterProgressPutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/ChapterSourceOrderPutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/HistoryLastReadPutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/MangaCoverLastModifiedPutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/MangaFavoritePutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/MangaFlagsPutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/MangaLastUpdatedPutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/MangaTitlePutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/MangaViewerPutResolver.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderColorFilterSheet.kt
- app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt
- Update Okio 2.9.0 -> 2.10.0 ([changelog](https://github.com/square/okio/blob/master/CHANGELOG.md))
- Utilize contentValuesOf and getSystemService KTX functions (see [here](https://developer.android.com/reference/kotlin/androidx/core/content/package-summary))
- For ReaderColorFilterSheet, I was conflicted between using the extension functions [components](https://developer.android.com/reference/kotlin/androidx/core/graphics/package-summary#component1) and the extension properties [argb](https://developer.android.com/reference/kotlin/androidx/core/graphics/package-summary#alpha). Please advise.
> Update Okio, use more KTX stuff

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/navigation/RightAndLeftNavigation.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonConfig.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonDefaultNavigation.kt
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
and remove default navigation classes in favor of the navigation classes
closes #4391
> Add Right and Left for navigation mode

- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt
closes #4487
Adds Right and Left to reader settings 
| Before | After |
|---|---|
| ![Screenshot_1613390377](https://user-images.githubusercontent.com/6576096/107944020-d2a48000-6f8d-11eb-984e-42b035fb4e86.png) | ![Screenshot_1613390227](https://user-images.githubusercontent.com/6576096/107943988-c7e9eb00-6f8d-11eb-84ee-7d211b918196.png) |
> Add Right and Left to reader settings

- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/SearchController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/SourceSearchController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt
Allows migration when searching specific source after original migration search. Closes #4587
> Implement migration for source search

- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/SearchController.kt
> Fix migration due to variable shadowing

- app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/BaseController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/presenter/BasePresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/SourceController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourcePresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/search/SettingsSearchPresenter.kt
Still learning the ropes with Android\Kotlin coming from Delphi so if something isn't Kotlin-y enough let me know :)
> Add onPause\onResume persistence to searchView. Fixes issue #3627

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt
fixes #4738
Webtoon doesn't insert pages so it's not affected by this
---
Before:
https://user-images.githubusercontent.com/6576096/112858094-d6114800-90b1-11eb-9588-1fa3a30dfe49.mp4
After:
https://user-images.githubusercontent.com/6576096/112857574-45d30300-90b1-11eb-8d6c-6a8f901b1964.mp4
> Remove insert page when dual page split get turned off

- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/MangaQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/RawQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySort.kt
- app/src/main/res/values/strings.xml
> add sort by date fetched in library

- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryItem.kt
Closes #3773
Co-Authored-By: jobobby04 <jobobby04@gmail.com>
> Search in library include manga description

- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
Move two deletion functions that use unifile for deletion to the IO context to prevent main thread freezing.
> Move deletion actions to the IO thread

- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt
Fix #4802's copy pasta derp. I blame myself.
> BrowseSourceController: Fix navigation bar insets not properly applied

- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt
> Fix source SearchView stuck open until query submitted

- app/src/main/AndroidManifest.xml
- app/src/main/res/values/themes.xml
Added a new theme for the Webview activity just to change the icon color in the status bar
> Status bar icon colors in webview activity

- app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
> MainActivity: Show bottom nav when the tab page is changed

- app/src/main/res/drawable-v26/sc_collections_bookmark_48dp.xml
- app/src/main/res/drawable-v26/sc_explore_48dp.xml
- app/src/main/res/drawable-v26/sc_history_48dp.xml
- app/src/main/res/drawable-v26/sc_new_releases_48dp.xml
- app/src/main/res/drawable/sc_collections_bookmark_48dp.xml
- app/src/main/res/drawable/sc_explore_48dp.xml
- app/src/main/res/drawable/sc_history_48dp.xml
- app/src/main/res/drawable/sc_new_releases_48dp.xml
Also swap the color.
before
after
> Use adaptive icon for app shortcuts

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsDownloadController.kt
- app/src/main/res/values/strings.xml
Basically feature request #4684
added the setting for that, so people can choose if they want to.
> Setting: Creates folders according to manga title

- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt
> Add automatic setting to reader settings

- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadPresenter.kt
- app/src/main/res/menu/download_single.xml
- app/src/main/res/values/strings.xml
yoink from J2K
Co-Authored-By: Jays2Kings <jays@outlook.com>
> Add cancel all for series in download queue

- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/SearchController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/SearchPresenter.kt
However I'm still not sure if we should change the copy behavior too, since the copied manga is technically still belongs in the library.
> Open migrated/copied manga right away

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
- app/src/main/res/values/strings.xml
Add option to hide "Updates" and "History" buttons. Add code in showBottomNav function for manipulate visibility of buttons "on a fly"
> Add option to hide "Updates" and "History" buttons

- app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt
looks easy, so im doin it myself LOL
closes #5089
> add text progress to library update notification 

- app/build.gradle.kts
- app/src/main/res/layout/categories_item.xml
- app/src/main/res/layout/common_dialog_with_checkbox.xml
- app/src/main/res/layout/download_item.xml
- app/src/main/res/layout/global_search_controller_card.xml
- app/src/main/res/layout/navigation_view_checkbox.xml
- app/src/main/res/layout/navigation_view_checkedtext.xml
- app/src/main/res/layout/navigation_view_radio.xml
- app/src/main/res/layout/reader_activity.xml
- app/src/main/res/layout/reader_color_filter_settings.xml
- app/src/main/res/layout/section_header_item.xml
- app/src/main/res/layout/source_list_item.xml
- app/src/main/res/layout/updates_item.xml
- app/src/main/res/values-sw600dp/dimens.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
Also added paddings to some buttons to make its touch target larger
> Remove material-design-dimens

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSheet.kt
> Fixed tracker sheet corner radius not being rounded on start

- app/build.gradle.kts
- app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupCreateService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/notification/NotificationReceiver.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/webview/WebViewActivity.kt
- buildSrc/src/main/kotlin/AndroidConfig.kt
This will help with the transition to targetSdk 30 (if we ever get there).
> Bump compileSdk to 30

- app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/OneWayFadeChangeHandler.kt
Introduced in c68e7c8da78309a0b091c11379a8da5c6222572d
> Prevent view from being removed if a to is found (#5135)

- app/src/main/java/eu/kanade/tachiyomi/util/preference/PreferenceDSL.kt
- app/src/main/java/eu/kanade/tachiyomi/widget/preference/AdaptiveTitlePreferenceCategory.kt
[Before](https://user-images.githubusercontent.com/12537387/119318425-7dba8900-bca3-11eb-84bf-1c2a3697c87c.png)
[After](https://user-images.githubusercontent.com/12537387/119318384-70050380-bca3-11eb-9f9d-02fe326c8a7b.png)
> Remove top margin of PreferenceCategory if no title set

- app/src/main/java/eu/kanade/tachiyomi/widget/sheet/BottomSheetViewPager.kt
- app/src/main/res/layout/common_tabbed_sheet.xml
> TabbedBottomSheetDialog: Fix scrollable pages

- app/src/main/java/eu/kanade/tachiyomi/data/track/TrackService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/Bangumi.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/Kitsu.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/komga/Komga.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeList.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/shikimori/Shikimori.kt
removed the add function from TrackService.kt as it's not used except within the tracker implementations
> Refactor TrackService.kt to remove unused `add` function

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
Totally not stolen from other forks.
Although to cover all my bases I co-author all people who adapted the theme in any form.
Neko, J2K and Tako
| Green Apple |
| ------------- |
| ![Green Apple](https://user-images.githubusercontent.com/10836780/119436068-cb72d800-bd1b-11eb-8a29-1c0305dabba3.png) |
> Added "Green Apple" theme

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoHeaderAdapter.kt
- app/src/main/res/layout/manga_info_header.xml
- app/src/main/res/xml/manga_info_header_scene.xml
I would say this closes #2130, it doesn't add anything fancy like pinch to zoom but adds the ability to view/enlarge the cover to view it in its full glory.
https://user-images.githubusercontent.com/6576096/120349304-4b8dd480-c2fe-11eb-90a1-7261238cb1b2.mp4
This will be available to phone and tablet until I get around to changing the layout for tablets to have a larger cover instead of a tiny one
> Tap to enlarge cover

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoHeaderAdapter.kt
- app/src/main/res/layout-w720dp/manga_info_header.xml
- app/src/main/res/values-sw600dp-port/dimens.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/xml/manga_info_header_scene.xml
- app/src/main/res/xml/manga_info_header_scene_sw600dp.xml
- app/src/main/res/xml/manga_summary_section_scene.xml
Also, fix bug when opening from source (fixes #5295)
--- 
Cover does expand when tapped
| Porait | Landscape |
|---|---|
| ![pixelc-port](https://user-images.githubusercontent.com/6576096/120766114-31304280-c51a-11eb-879e-706ddc337da8.png) | ![pixelc-land](https://user-images.githubusercontent.com/6576096/120766118-32616f80-c51a-11eb-8dfe-bb1704ac2165.png) |
| ![Screenshot_1622793040](https://user-images.githubusercontent.com/6576096/120766263-5755e280-c51a-11eb-80b6-c6c337d66bc4.png) | ![Screenshot_1622793035](https://user-images.githubusercontent.com/6576096/120766264-57ee7900-c51a-11eb-89cf-cf15ee654d3a.png) |
| Porait | Landscape |
|---|---|
| ![z2-port](https://user-images.githubusercontent.com/6576096/120766035-1bbb1880-c51a-11eb-88fa-834a0ede8f90.png) | …
> Make cover bigger on tablet UI

- app/src/main/res/layout/manga_info_header.xml
The gradient was not aligned to the bottom of the backdrop
> Fix gradient not being smooth

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChapterDownloadView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesPresenter.kt
> Fix download status not updated properly after starting batch download

- app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadHolder.kt
- app/src/main/res/layout/categories_item.xml
- app/src/main/res/layout/download_item.xml
[Before](https://user-images.githubusercontent.com/12537387/121230629-ae144100-c8b9-11eb-871d-88ae57beff76.png)
[After](https://user-images.githubusercontent.com/12537387/121230645-b3718b80-c8b9-11eb-8e19-3bbe11983e3e.png)
> Add background to draggable items

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/themes.xml
From the moment when colorful themes were added to the app, I will also add my own contribution to this. I would like to have an orange-pinkish theme implemented in the app, the color was taken from the hair color of the character Yotsuba Nakano from the manga "5-toubun no Hanayome". As for me, the theme looks juicy.
> Added "Yotsuba" theme

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt
> Fix incorrect toolbar text color after theme change

- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadService.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/base/BaseChapterHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/base/BaseChaptersAdapter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesPresenter.kt
- app/src/main/res/menu/chapter_download.xml
- app/src/main/res/values/strings.xml
download now for selected chapter
from j2k
Closes #4607
Co-Authored-By: Jays2Kings <jays@outlook.com>
> add start download now

- app/src/main/res/color/ripple_colored.xml
- app/src/main/res/layout-sw720dp/main_activity.xml
- app/src/main/res/layout/track_item.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
Resolves #5428 
Resolves #5429
Resolves #5430
> Fix issues on older API versions and tablets

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/util/view/WindowExtensions.kt
- app/src/main/java/eu/kanade/tachiyomi/widget/sheet/BaseBottomSheetDialog.kt
- app/src/main/res/layout/reader_activity.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/themes.xml
> Match ReaderActivity theme with the rest of the app

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ReaderTransitionView.kt
- app/src/main/res/layout/reader_transition_view.xml
> Reader fixes after #5450

- app/src/main/res/values/strings.xml
> Change wording for "Per-category display setting"

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
> Fix reader toolbar alpha applied to other components outside its activity

- app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionPresenter.kt
| Before | After |
| --- | --- |
| Genkan.io (all.genkanio) | Bilibili Comics (en.bilibilicomics) |
| MangaDex (all.mangadex) |  CatManga (en.catmanga) |
| Bilibili Comics (en.bilibilicomics) | Genkan.io (all.genkanio) |
| CatManga (en.catmanga) | MangaDex (all.mangadex) |
> Sort Installed, Update, Untrusted Extenion by Name in Extensions Tab

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSearchHolder.kt
- app/src/main/res/layout/track_search_dialog.xml
- app/src/main/res/layout/track_search_item.xml
Based on feedbacks
[Preview](https://user-images.githubusercontent.com/12537387/124310442-602be980-db96-11eb-9c8e-7bd08707a5b3.png)
> Track search dialog adjustments

- app/src/main/java/eu/kanade/tachiyomi/App.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseRxActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseViewBindingActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
- app/src/main/java/eu/kanade/tachiyomi/util/system/LocaleHelper.kt
Fixes broken dark mode when custom locale is selected. Related issue on [J2K](https://github.com/Jays2Kings/tachiyomiJ2K/issues/886).
> Simplify locale override

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
<table>
<tr>
<td>Light
<td>Dark
<td>Amoled
<tr>
<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/861917623104438302/Screenshot_1625567369.png">
<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/861917621044772904/Screenshot_1625567389.png">
<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/861917616494739496/Screenshot_1625567410.png">
<tr>
<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/861876979443302400/Screenshot_1625557743.png">
<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/861877101413662720/Screenshot_1625557806.png">
<td><img src="https://cdn.discordapp.com/attachments/825346400953827349/861877104462004224/Screenshot_1625557835.png">
<tr>
<td><img …
> add Yin Yang Theme

- app/src/main/res/values-night/colors.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
As pointed out by @ivaniskandar on the dev channels. This better optimizes how the variant of the theme is written.
> Optimize the Green Apple theme variant

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
> Hide the reader seekbar for single-page chapters

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderNavigationOverlayView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
This being the reader navigation overlay that's shown when reading mode is changed.
> Don't show navigation overlay if tap navigation is disabled

- app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
> Fix transparent system bars after MainActivity recreated

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSheet.kt
- app/src/main/java/eu/kanade/tachiyomi/util/lang/DateExtensions.kt
> Fix incorrect saved tracker dates

- app/src/main/java/eu/kanade/tachiyomi/App.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
Potentially resolves #5468
I can't replicate the issue as stated on the issue report (probably because of #5533) but I'm able to replicate similar behavior by doing cold run.
> Apply default night mode earlier

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoHeaderAdapter.kt
| Before| After |
| ------- | ------- |
| ![Screenshot_1631953045](https://user-images.githubusercontent.com/6576096/133881978-15ec1088-0d3b-4395-90f9-3380a7f7f159.png) | ![Screenshot_1631952886](https://user-images.githubusercontent.com/6576096/133881908-a77d1614-7b68-4c0a-9855-904de49d91d4.png) |
> Remove spaces at end of line before removing multiple new lines

- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt
- app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedController.kt
- app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt
- app/src/main/res/values/strings.xml
added automatic tablet ui option; useful for foldables like the Z Fold 3
tested in emulator and on my phone
> Added tabletUI option: "Automatic"

- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAppearanceController.kt
- app/src/main/res/values-night/midnightdusk_colors.xml
- app/src/main/res/values/midnightdusk_colors.xml
Dark | Pure Black
---|---
I don't think light theme needs tweaking.
> Tweak Midnight Dusk colors

- app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> Fix search inputs accepting formatted text

- app/src/main/java/eu/kanade/tachiyomi/data/database/queries/MangaQueries.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values/strings.xml
When adding a manga to your library, the app will go through the library and compare the names of all mangas until either a match is found, or the end of the list is reached.
1) Nothing got tagged, so it will just be added to the library
2) A manga with the same name AND from a different source was found.
A dialog box will appear, informing the user about this and giving them 3 options:
- "Add"
- "Cancel"
- and "Show manga"
I have tested it myself, and it appears to be working. However, I have not been able to test the German translation, since I can't seem to be able to change the language of the app 🤔 
The detection method is very simple (just comparing the names, ignoring letter casing). So it will neither trigger if the names are in different languages, nor if they are just slightly …
> Detect identical mangas when adding to library

- app/src/main/java/eu/kanade/tachiyomi/network/DohProviders.kt
- app/src/main/java/eu/kanade/tachiyomi/network/NetworkHelper.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedController.kt
> Add Quad9 DOH provider

- app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt
Fixed the history page use the wrong offset case missing some item.
> Fixed the wrong offset

- app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
Closes https://github.com/tachiyomiorg/tachiyomi/issues/1561
Had an idea on how to handle this while keeping the same behavior, decided to just PR it instead of add it to my fork first since its small.
> Handle 1000+ pages properly in the downloader

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt
> Prevent scrolling outside bounds in webtoon/vertical reading mode

- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
_Why download chapters that will be skipped later in the reader?_
Maybe resolves #8879
> MangaScreenModel: Make download function follow reader preference

- app/src/main/java/eu/kanade/presentation/library/components/LibraryContent.kt
> Fix crash in library when selected category is deleted

- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ReaderPageImageView.kt
"true center" Zoom start position 
Changed zoom position to get true center value.
Closes #8747
> Make center zoom start vertically centered too

- app/src/main/java/eu/kanade/presentation/library/LibrarySettingsDialog.kt
> fix: grid size slider

- presentation-core/src/main/java/tachiyomi/presentation/core/components/AdaptiveSheet.kt
Fixes #9922 
https://github.com/tachiyomiorg/tachiyomi/assets/92362239/98005543-471e-4532-bb52-6b75b135c3d5
> Fix checkboxes not working after scrolling in filter sheet
