tachiyomiorg/tachiyomi

app/src/main/res/layout/item_chapter.xml
Fixes chapter number not being visible on long manga names (see https://github.com/inorichi/tachiyomi/issues/54)
A nicer, more complex solution might be to split the chapter name between manga name and chapter number and only elipsize the manga name on the end, leaving the chapter number visible
=> elipsize chapter list in the middle

app/src/main/java/eu/kanade/tachiyomi/util/ChapterRecognition.java, app/src/test/java/eu/kanade/tachiyomi/ChapterRecognitionTest.java
Adds supports for the follow scenarios:
- chapter versions directly attached to the chapter number (chapter 002v2)
- chapter titles with non-freestanding numbers in the title (chapter 002 foobar the 2nd)
- subchapter denoted by an alpha prefix (chapter 002a, chapter 002b)
- chapter titles with arc numbers (chapter 123 - foo arc 002)
- chapters with numbers in part descriptions (chapter 002 part 001)
This fixes all chapter number issues I've run into so far
=> Improve chapter number parsing

README.md
The worst issue reports come from newly created github accounts. Such users probably look around the page, see issue, click there, see New issue, click there, see a textbox and they start writing, ignoring anything else (like `Please review the guidelines for contributing to this repository.`).
Hope it helps
=> Make CONTRIBUTING.md more visible

app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadFragment.kt
Hide the clear butten when all downloads have finished.
=> Hide clear button

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/vertical/VerticalViewPagerImpl.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - Dead stores should be removed
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1854
M-Ezzat
=> squid:S1854 - Dead stores should be removed

app/src/main/java/eu/kanade/tachiyomi/ui/backup/BackupFragment.kt
Same MIME for restore/backup, so 3rd party applications like Google Drive find the proper files.
MIME changed to proper type for json files.
=> Fixed backup/restore for 3rd party applications

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/vertical/VerticalViewPagerImpl.java, app/src/main/java/eu/kanade/tachiyomi/util/DynamicConcurrentMergeOperator.java, app/src/main/java/eu/kanade/tachiyomi/widget/EndlessGridScrollListener.java, app/src/main/java/eu/kanade/tachiyomi/widget/EndlessListScrollListener.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2039 - Member variable visibility should be specified
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2039
M-Ezzat
=> squid:S2039 - Member variable visibility should be specified

app/src/main/java/eu/kanade/tachiyomi/data/database/tables/ChapterTable.java, app/src/main/java/eu/kanade/tachiyomi/data/database/tables/MangaSyncTable.java, app/src/main/java/eu/kanade/tachiyomi/util/AndroidComponentUtil.java, app/src/main/java/eu/kanade/tachiyomi/util/ChapterRecognition.java, app/src/main/java/eu/kanade/tachiyomi/util/GLUtil.java, app/src/main/java/eu/kanade/tachiyomi/util/Parser.java, app/src/main/java/eu/kanade/tachiyomi/util/UrlUtil.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - Utility classes should not have public constructors
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1118
M-Ezzat
=> squid:S1118 - Utility classes should not have public constructors

app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAboutFragment.kt
Accidentally removed the manual check. This means you can't update within the app when 2.1 is installed.
=> Release version manual update hotfix.

app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Batoto.java, app/src/main/java/eu/kanade/tachiyomi/data/source/online/russian/Mangachan.java
This pull request is focused on resolving occurrences of Sonar rule pmd:UseIndexOfChar - Use Index Of Char
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:UseIndexOfChar
M-Ezzat
=> pmd:UseIndexOfChar - Use Index Of Char

app/build.gradle
Fix issue when building version other than the latest one. Occurs when there are two commits in short timespan
=> Wrong versionName when not building latest version

app/src/main/res/values/strings.xml
All English manga sources use either Ongoing or Completed, so Tachiyomi using a different term for ongoing manga feels off.
=> Rename "Only update incomplete manga" string to "ongoing"

app/src/main/java/eu/kanade/tachiyomi/injection/ComponentReflectionInjector.java, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/vertical/VerticalViewPagerImpl.java, app/src/main/java/eu/kanade/tachiyomi/util/DiskUtils.java
This pull request is focused on resolving occurrences of Sonar rules squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order
squid:S1943 - Classes and methods that rely on the default system encoding should not be used
squid:S1066 - Collapsible "if" statements should be merged
You can find more information about the issues here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1213
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1943
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1066
M-Ezzat
=> Multiple quality improvements - squid:S1213, squid:S1943, squid:S1066

app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangahere.kt
Using MangaHere on pulled manga led to a NullPointerError and [corresponding non-informative toast](http://imgur.com/wCzQtMK). This gives an empty page list instead (try reading a chapter of Nisekoi to test), which is technically true and far more informative.
Giving a reason to the user beyond "Empty Page list" would be a good idea in the future (this seems to be one holdup for #220), but there doesn't seem to be an obvious place to put it without touching the base classes.  In the meantime, this one-line fix is far more useful than null pointer errors.
=> Handle pulled manga in MangaHere

app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangasee.kt
Current selector is not precise enough and is duplicating the last chapter in chapter list.
=> Update Mangasee chapter selector

app/src/main/java/eu/kanade/tachiyomi/data/mangasync/myanimelist/MyAnimeList.kt
MAL has added support for HTTPS/TLS and is discontinuing HTTP based API endpoints. All API endpoints are to be HTTPS.
As per [https://myanimelist.net/forum/?topicid=1543851](https://myanimelist.net/forum/?topicid=1543851)
> Also, in order to allow our 3rd party developers ample time to update their applications, we’ve decided to allow our API to support both HTTP and HTTPS for about 3 weeks. Please update your application(s) as soon as possible. By mid-September, the API endpoints will only use HTTPS.
I have tested this changed by adding a new manga to MAL, updated chapters, and changed MAL status and rating. However, no further testing has been conducted.
I have confirmed that  communication to MAL is via TLS using a packet capture, compared to HTTP before.
=> MAL switched to SSL/HTTPS

app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangasee.kt
Now properly filters out chapter numbers with dots and completed series.
=> Better recent updates regexp for Mangasee

app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangahere.kt
Fixes #522 
A cleaner implementation would remove the Manga name from the beginning of the chapter title, but an instance of Manga is not available in `chapterFromElement` it would require a few more changes to be feasible.
=> Added Volume and Title to chapters from MangaHere

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/util/ChapterSourceSync.kt, app/src/main/res/values/keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/pref_downloads.xml
Fixes #116
The changed `readded` logic was needed to prevent all non-read chapters from sources such as MangaFox being detected as new
=> Add optional to automatically download new chapers

app/src/main/java/eu/kanade/tachiyomi/App.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralFragment.kt, app/src/main/java/eu/kanade/tachiyomi/util/LocaleHelper.kt, app/src/main/res/values/arrays.xml, app/src/main/res/values/keys.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/pref_general.xml
Implements request #558 
In my opinion I don't think it's that much of a mess. There are two deprecated java functions used, these cannot be changed unless the min android API is set to 17 instead of 16.
Feel free to point out any changes needed or just close if this isn't something you want.
=> Implement language switcher

app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangahere.kt
Fixes #571
The text on the popular manga page of Mangahere contains escaped HTML characters. The title attributes of the links do not contain them.
=> Using title instead of text for Mangahere titles

app/src/main/java/eu/kanade/tachiyomi/data/source/model/Filter.kt, app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Batoto.kt, app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangafox.kt, app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangahere.kt, app/src/main/java/eu/kanade/tachiyomi/data/source/online/english/Mangasee.kt, app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/CatalogueNavigationView.kt
This PR adds a sorting catalog filter with an appearance similar to the library filter view.
It occupies more screen space compared to a Spinner, if despite this it is still ok I will update the other catalogs (for now only MangaFox is updated).
=> Add Sort filter [Catalogs]

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/eu/kanade/tachiyomi/data/glide/MangaModelLoader.kt, app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt, app/src/main/java/eu/kanade/tachiyomi/source/SourceManager.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recently_read/RecentlyReadHolder.kt, app/src/main/java/eu/kanade/tachiyomi/util/ChapterRecognition.kt, app/src/main/java/eu/kanade/tachiyomi/util/DiskUtil.kt, app/src/main/java/eu/kanade/tachiyomi/util/ZipContentProvider.kt, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values/strings.xml
This source allows to read locally stored mangas in zip/cbz/folder format.
The zip/cbz/folder files of each manga must be stored in a subdirectory of `/sdcard/Tachiyomi/mangas/`. As example:
```
/sdcard/Tachiyomi/mangas/MANGA_TITLE_1/chapter_1.zip
/sdcard/Tachiyomi/mangas/MANGA_TITLE_1/chapter_2.zip
/sdcard/Tachiyomi/mangas/MANGA_TITLE_2/chapter_1.cbz
/sdcard/Tachiyomi/mangas/MANGA_TITLE_2/cover.jpg
/sdcard/Tachiyomi/mangas/MANGA_TITLE_3/chapter_1_folder
/sdcard/Tachiyomi/mangas/MANGA_TITLE_3/chapter_2_folder
...
```
If a `cover.jpg` file is present it is used as cover for the manga.
The source extracts the zip/cbz files to the chache directory . A better option would be to directly read the image files from the .zip by using `java.net.URL("jar:file://sdcard/Tachiyomi/mangas/m1/c1.zip!/i1. …
=> Local manga in zip/cbz/folder format

app/src/main/java/eu/kanade/tachiyomi/source/online/english/Mangasee.kt
Mangasee needs proper headers for data requests
It is either we need to change headers for their new domain (old links forward to new domain) or change the source url yet again.
Maybe changing the url is better in the long run as currently only catalog breaks with old domain.
=> Mangasee catalog fix

app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadNotifier.kt
Escape the manga title before using it in the regex statements in the download notifier.
Fixes #709
=> Prevent some manga breaking the download notifier

app/src/main/java/eu/kanade/tachiyomi/source/SourceFactory.kt, app/src/main/java/eu/kanade/tachiyomi/source/SourceManager.kt
Add the ability to specify multiple source classes in a single extension apk.
Source classes should be separated by `;`. Spaces are permitted between source classes. Old sources are backwards compatible.
SourceFactories can also be defined after this patch. SourceFactories allow extensions to specify a class that can create multiple sources when loaded. (Requires PR: https://github.com/inorichi/tachiyomi-extensions-lib/pull/1)
**Not sure if we should bump the version number of the source library? I considered this because new extension sources that contain multiple source classes will not be compatible with old versions of Tachiyomi.**
Also did a bit of code cleanup and increased verbosity of error messages
=> Allow multiple sources in each extension source apk

app/src/main/java/eu/kanade/tachiyomi/source/online/english/Batoto.kt
Some links now use https rather than http, so parsing was affected. I don't know if this is a permanent change on Batoto's end, but it does fix the issue of not being able to load any manga from Batoto in Tachiyomi (built from master branch). Fixes #872.
=> Fix issues with Batoto

app/src/main/java/eu/kanade/tachiyomi/source/online/english/Mangafox.kt
@inorichi fixed issue you were mentioning about warning div.
Verifies the warning div contains licensed before assigning it as licensed.
vs adult non licensed
=> added licensed element check for MangaFox

app/src/main/java/eu/kanade/tachiyomi/source/online/english/Mangahere.kt
Fixes issue #1050.
An extra page exists at the end of all chapters on Mangahere called "featured.html", but that page has no image, so downloading always fails. I'm not sure when this was added or when it might be removed, but it is no longer added to a chapter's page list.
=> Fix extra (advertisement) page being added in Mangahere.

app/src/main/res/layout/reader_activity.xml
#1055
Not noticeable on screen shots here's a before and after on actual pixel 2 XL.
before:
after:
=> page number cut off in rounded screen devices

app/src/main/java/eu/kanade/tachiyomi/source/online/english/Kissmanga.kt
Address issue #1053
Thanks @cylonu87 for basis of conversion code.
before:
after:
=> added Cloudflare email obfuscation bypass for kissmanga

app/src/main/java/eu/kanade/tachiyomi/source/online/english/Readmangatoday.kt
Hello!
Readmangatoday recently updated their HTML. So I updated the selector for the images.
This PR closes #1070
=> Fix crash when downloading manga from Readmangatoday

app/src/main/java/eu/kanade/tachiyomi/source/online/english/Batoto.kt
Fixes #1087. May also fix #1034, but I'm not sure.
Batoto added Cloudflare protection recently (I was sure they had already had Cloudflare, but apparently I was wrong), which interfered with logging in, loading the Popular/Latest lists, and downloading pages in chapters that were already in the library. Overriding HttpSource#client with network.cloudflareClient resolves all of these issues.
=> FIx Batoto issues with logging in and loading lists/pages.

app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupCreateService.kt, app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupCreatorJob.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsBackupController.kt, app/src/main/res/values/strings.xml
This closes #900 
~Probably needs some more testing and stuff. But tested working on Android 8.0.0.~
~Fix is using a correct URI call + creating the directory through:~
~`val autoDir = dir.createDirectory(getString(R.string.automatic_backup))`~
~If you have a cleaner solution let me know ;)~
Tested working on: API 19,26 and 27
=> Fix automatic backups

app/src/main/java/eu/kanade/tachiyomi/source/online/english/Mangafox.kt
Fixed in extensions as well - tachiyomi seems to prefer built-in source over external
=> [Mangafox] update mangafox URL for built-in source

app/src/main/res/layout/catalogue_global_search_controller.xml, app/src/main/res/layout/catalogue_global_search_controller_card.xml, app/src/main/res/layout/catalogue_recycler_autofit.xml, app/src/main/res/layout/library_grid_recycler.xml, app/src/main/res/layout/recently_read_controller.xml
As you can see below, when scrolling, the RecyclerViews are clipping to the padding, bringing my OCD great distress.
Left = Before
Right = After
I have circled the points of interest in red.
Notice that outrageous black line that cuts off the manga covers. It brings me great pain and I request to immediately abolish it through this PR!
*On a more serious note:* If that's actually the intended behavior, then feel free to close this PR.
=> Fix padding on RecyclerViews

app/src/main/java/eu/kanade/tachiyomi/network/CloudflareInterceptor.kt
Cloudflare is switching from Server = cloudflare-nginx to Server = cloudflare.
Kissmanga still uses the old version
Mangago uses the new version 
added support for both server names
https://github.com/inorichi/tachiyomi-extensions/issues/150
=> Fixes minor cloudflare issue

app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCatalogueController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoController.kt, app/src/main/res/drawable/ic_add_to_library_24dp.xml, app/src/main/res/drawable/ic_in_library_24dp.xml, app/src/main/res/layout/manga_info_controller.xml, app/src/main/res/values/strings.xml
Address fixes requested in #1154 also adds the toast message when long click manga in the catalog view.
=> Address #1154

app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsBackupController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsDownloadController.kt, app/src/main/java/eu/kanade/tachiyomi/util/ContextExtensions.kt
When using `Intent.ACTION_CREATE_DOCUMENT` on SDK >= Lollipop there is no
guarantee that the ROM supports the built in file picker such as MIUI
A discord user had this issue which caused Tachiyomi to crash when trying to start a backup
=> Handle ActivityNotFoundException

app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoController.kt, app/src/main/java/eu/kanade/tachiyomi/util/ChapterRecognition.kt, app/src/test/java/eu/kanade/tachiyomi/data/database/ChapterRecognitionTest.kt
Wasnts matching on  vol. 1 ch. 10 previously so mangadex last chapter was showing volume number.
Changed details page to show blank instead of -1 or 0 for manga without chapters or with chapters but has no numbers like one shots.
Old  
New
=> Fix chapter recognition regex and detail number

app/src/main/java/eu/kanade/tachiyomi/source/online/english/Mangahere.kt
mangahere hides licensed content so updated to mark status licensed when available
also updated url to .cc since .co was just redirecting
=> Mangahere licensed status and url

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PageView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerReader.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonReader.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt, app/src/main/res/values/strings.xml
solves https://github.com/inorichi/tachiyomi/issues/691
Pretty simple, the SubsamplingScaleImageView has a builtin for double tap anim speed.
=> Add option to change double tap animation speed in the reader

app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/CatalogueController.kt
Improving the new user experience.
Just ask for storage access when browsing the catalogues, as the `LocalSource` is always part of it.
> New user, wanted to use Tachiyomi to view a `.cbr` file.
Installed Tachiyomi, googled how to view local comics, did the whole `Tachiyomi/local` thing.
Didn't see anything, then remembered that I was never asked for sdcard permission, manually gave permission via system settings, then had to restart the app and go to local storages again.
=> Ask for permission if necessary when browsing the catalogues

app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/SourceHolder.kt
Currently clicking latest pops up toast message of whatever the writer of the source put in the exception.  This hides it instead
=> Hide Latest button in catalog when source doesnt support latest

app/src/main/res/layout/chapters_item.xml
Start/End not supported for android 16. #1220
=> Adjust 3 dot chapter menu to support Android 16

app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/LangHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionDetailsController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionViewUtils.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsSourcesController.kt, app/src/main/java/eu/kanade/tachiyomi/util/LocaleHelper.kt
Adjusted locale from external sources and catalogues to use the same code.  Originally was planning to use it an kotlin extension but decided to stuff in in the Locale Helper for consistency sake.
=> Added country/region support for locale when displayed for sources

app/src/main/java/eu/kanade/tachiyomi/network/NetworkHelper.kt
This fixes connection errors with some servers on Android 4.1-4.4. In particular I noticed this with the _xkcd_ extension.
More info on https://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/
=> Enable TLS 1.1 and TLS 1.2 on Android KitKat (and older)

app/build.gradle, app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupManager.kt, app/src/main/java/eu/kanade/tachiyomi/data/backup/serializer/TrackTypeAdapter.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/DbOpenHelper.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/mappers/TrackTypeMapping.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/models/Track.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/models/TrackImpl.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/tables/TrackTable.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistInterceptor.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistModels.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/OAuth.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/Kitsu.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuModels.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/model/TrackSearch.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyanimelistApi.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/AnilistLoginActivity.kt, app/src/main/res/values/strings.xml
Switches to using the Anilist v2 API.
Login is now done by implicit grant and tokens are good for one year.
Users will need to login again after token expiration.
"clientId" on line 289 of AnilistApi.kt should be changed to Tachiyomi's
own client ID number.
=> Implement Anilist API v2 (closes #1159)

app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt
Addresses issue #1434.
For some reason, AniList API v2 was not returning the correct search results when query arguments `type: MANGA` and `format: MANGA` were both present. Removing `format: MANGA` makes the query return the correct results. Specifically, it returns Korean manhwa as well as Japanese manga, where it was not always returning manhwa before. For instance, Noblesse (manhwa) and One Piece (manga) were both showing fine, but Lookism (manhwa) was not.
I changed the format argument to `format_not_in: [NOVEL]` because there are only three manga related MediaFormats: MANGA, NOVEL, and ONE_SHOT. Filtering out NOVEL entries leaves manga and one-shots, both of which are relevant to Tachiyomi, and which allows all manga and manhwa entries (that I have so far tested) to show in the …
=> Change AniList search query to show some previously hidden entries.

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt, app/src/main/java/eu/kanade/tachiyomi/util/ChapterSourceSync.kt
Update manga.last_update on ChapterSourceSync.syncChaptersWithSource() rather than only during LibraryUpdateService.updateChapterList()
Viewing a manga's info page for the first time forces a chapter sync.
Prior behavior would cause new chapters to be retrieved for that manga, but with manga.last_update remaining at 0 (until a library update occurred in which chapters were added).
New behavior updates last_update any time the chapters are changed via syncChaptersWithSource().
=> Update manga.last_update on ChapterSourceSync.syncChaptersWithSource()

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
On systems that support badging, this makes the app icon's badge show the count of updates rather than just (1).
=> Set notification number for library updates to number of new updates

app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/global_search/CatalogueSearchHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/global_search/CatalogueSearchItem.kt, app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/global_search/CatalogueSearchPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/migration/SearchPresenter.kt
Verified that this does not affect the order of the other elements.
I've also verified that both copy and migrate work for same-source migration, even if you select the manga you've already got selected.
=> For migration, put the selected source at the top of the search list instead of excluding it

app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoPresenter.kt
(Using a toast)
This is only for MangaInfoController's initial manga view and/or swipe refresh, _not_ for other places that fetch manga info (e.g. catalog view).
=> Handle manga info fetch errors in the same way as chapter fetch errors

app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistModels.kt
**App version:**
0.7.4
**Issue/Request:**
When using AniList with the 5-star rating mode, the website's raw ratings go 0, 10, 30, 50, 70, 90, while Tachiyomi's go 0, 20, 40, 60, 80, 100.
This results in ratings made on the website showing up as 1 star lower within the app due to the integer conversion, and ratings made within the app making website stats less clean:
(AniList's stats page still shows 100-point ratings in 5-star mode)
I checked the smiley scale as well, which goes 0, 35, 60, 85 vs. 0, 30, 60, 90 in the app.
=> AniList 5-star/smiley <-> 100-point values differ from the AniList website

app/src/main/java/eu/kanade/tachiyomi/source/online/english/Mangasee.kt
The old URL http://mangaseeonline.net is obsolete, the new URL is http://mangaseeonline.us
=>  Update mangasee URL 

app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt
This will help alleviate not being able to find manga with generic names
such as Monster.
This also adds the mission description to the Anilist search dialogue.
=> Update Anilist API search to return 50 results

build.gradle
Apparently the repository order may cause bugs for new projects on newer Android Studio versions:
https://stackoverflow.com/questions/51195242/failed-to-resolve-firebase-iid-interop
=> Fixed Gradle script bug on newer Android Studio versions

domain/src/main/kotlin/manga/model/Manga.kt
add dateAdded field.  This will allow future library view to sort by added date.
Should this be lateint?  to make setting it mandatory?  Or does the interactor ChangeMangaFavorite need to create a new manga object with the date when added to library.
=> 1.x - add DateAdded to Manga

app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistModels.kt
fix #1804
also this is my first PR.
It was fixed to `BuildConfig.BUILD_TIME`. so when it's stable, it only shows `2017-10-31`
What is fixed in a commit is 
1. Date parse error due to no paddings. (`AnilistApi.kt`, `AnilistModels.kt`). [Thanks to Flat in #1804](https://github.com/inorichi/tachiyomi/issues/1804#issuecomment-454407099)
2. Fixed value to actual dates. (`AnilistModels.kt`)
| From(stable) | To |
| - | - |
| <img src="https://user-images.githubusercontent.com/45893338/51181017-61f18c00-190d-11e9-8a3d-7c4800ec7fae.png" width="350px"/> | ![b](https://user-images.githubusercontent.com/45893338/51216046-5da58d00-1966-11e9-840f-80babf3a9588.png) |
Codes may dirty.
=> Fix date parsing error on Anilist search

app/src/main/java/eu/kanade/tachiyomi/util/ChapterSourceSync.kt
Hey, i found a bug. If source has custom prepareNewChapter -  this method: https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/util/ChapterSourceSync.kt#L54 will override this in library update.
=> Fix bug with update lib and parse chapters

app/src/main/AndroidManifest.xml, app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt, app/src/main/res/xml/searchable.xml
It can be used to speed up/automate manga searches from a known list, with automation apps (like Tasker/Automate). I thought of this with #1774, it could help mass import tracking lists - you could automate the search of items of your AniList for example.
Anyone can now say or type "Search *manga* in Tachiyomi", either to Google Assistant or directly on the Google app, and be redirected to the search results in Tachiyomi
Note about future UI improvements, 1.x or later :
Currently Tachiyomi's "global search" is made to search items in catalogs and not in the library. I believe it would be more relevant for a Google Search to show a search activity with Library results on top, and then Catalog results - basically, a global "global search to satisfy both the users searching something in …
=> Added search intent handler and Google Search Action, for the global search

app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCatalogueController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoController.kt, app/src/main/java/eu/kanade/tachiyomi/util/ContextExtensions.kt, app/src/main/res/menu/catalogue_list.xml
Adds "Open in browser" and "Open in web view" menu items to the top level catalogue view, allowing users to navigate to a HTTP source catalogue's base URL.
=> Add options to open catalogue in browser/webview

app/src/main/java/eu/kanade/tachiyomi/data/database/queries/MangaQueries.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/resolvers/MangaTitlePutResolver.kt, app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/global_search/CatalogueSearchPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/migration/MigrationPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/migration/SearchPresenter.kt
...and update local titles when migration occurs
Background: if a user, for whatever reason, gets an old/incorrect title for a manga, and that title is later corrected by the source (with the same URL), the user cannot update the local DB title until they unfollow the manga, clear the DB of unfollowed manga, and refollow the manga.
However, the potential solution of forcing titles to update on manga info update leads to the possible confusing situation where a manga's title randomly changes (from the end user's perspective).
Thus, this makes the act of changing a manga's title explicit (in that it's a part of migration flow), and makes migration trust the source rather than the local DB for manga titles.
=> Force Migration to display titles from source rather than from local DB

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderColorFilterSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderColorFilterView.kt, app/src/main/res/layout-land/reader_color_filter_sheet.xml, app/src/main/res/layout/reader_activity.xml, app/src/main/res/layout/reader_color_filter.xml, app/src/main/res/layout/reader_color_filter_sheet.xml, app/src/main/res/values-v28/arrays.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
This commit adds an user-configurable option to change the color filter blend mode.
In addition to the current default, it adds the following PorterDuff modes:
Overlay, Multiply, Screen, Lighten, Darken
Closes request/issue [#2002](https://github.com/inorichi/tachiyomi/issues/2002).
=> Add color filter blend modes

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
Fix sharing images, which generate very long image name for sharing. 
Currently ocures on readmanga parser - this manga: http://readmanga.me/neveroiatnye_prikliucheniia_djodjo_chast_8__djodjolion__cvetnaia_versiia_
=> Bugfix. Sharing images with very long name

.travis.yml
Most likely due to Travis starting to migrate default environment from trusty to xenial starting from 2 months ago. https://changelog.travis-ci.com/
=> Travis Builds Failing

app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/global_search/CatalogueSearchHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/global_search/CatalogueSearchPresenter.kt, app/src/main/res/drawable/ic_search_black_112dp.xml, app/src/main/res/layout/catalogue_global_search_controller_card.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-bn/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-in/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-ms/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-sc/strings.xml, app/src/main/res/values-sr/strings.xml, app/src/main/res/values-sv/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
Solves https://github.com/inorichi/tachiyomi/issues/1732 https://github.com/inorichi/tachiyomi/issues/1809
Not sure on the exact UI (i.e. keep or hide the catalogue title), and if whether or not this should be in settings (can probably just remove the nothing_found view if not).
Also didn't see any value in showing a loading circle for catalogues that error out, so changed it to return an empty result.
=> Hide Empty Search Results in Catalogues

app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
Changed the GitHub Wiki help link in the menu to link the website instead.
The actual `/help/` page it would now link to isn't completely feature-complete but it does it's most important job and can re redirect the user to the Guides or FAQ section if they so choose.
=> Change "Help" link from Github Wiki to Website

build.gradle
I can't believe this is an actual issue
https://github.com/jitpack/jitpack.io/issues/4002
Repro:
1. Clear out your gradle cache or do a fresh git clone
2. Try to build/sync
3. fail
=> fix jitpack shitting out

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
Sets Glide to use the GIF file loop count instead of always looping infinitely. Fixes #2240
=> Set glide to use the gif loop count

app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionGroupHolder.kt, app/src/main/res/menu/extension_main.xml
This is a quick implementation of searching for extensions. This PR adds a search menu icon on the extensions view, while also removing the extensions count per extensions group (because the count is set on ExtensionManager updates, which would be more expensive to recompute on every new search query). 
Closes #2202. 
Demo here:
https://imgur.com/rYwGVJK
=> Implemented extension search functionality.

app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCatalogueController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCataloguePresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
Default remains an implicit category, but is selectable in the 'default category to add to' setting and handled properly when only 1 non-implicit category exists.
I've tested most cases of this with a single user category as well as with multiple user categories, so it should be ready for review.
=> Allow 'Default' category as the default for adding manga

app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt
Currently when sending requests to the AniList API newline characters are included in the JSON payload `\n` due to the usage of raw strings. This strips `\n` and trims white space.
=> fix: Don't send newlines and whitespace in API calls

app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsDownloadController.kt, app/src/main/java/eu/kanade/tachiyomi/util/DiskUtil.kt
Closes #2191, #2104.
Still not sure why the parent `.nomedia` doesn't always get created or why it doesn't seem to do anything for some people, but this is indeed the easiest workaround.
=> Add .nomedia file in each chapter download folder

app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaWebViewController.kt, app/src/main/res/menu/web_view.xml, app/src/main/res/values/strings.xml
Adds Forward, Refresh, and Close actions to webview controller menu
-----------------------------------------------
Things before this should be merged:
- Do I need to null-check 'web' since view comes from getView() instead of a param?
- How do I add a 'close' menu item for the web view controller so that if a user gets stuck in e.g. an ad-loop they can force the whole WebView to close (as pressing back used to do here)?
=> Allow back button to navigate to previous URL in WebView

app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
fixes #2411
Chapters only autostart if the queue was empty when adding new chapters to it.  This way downloads still autostart when nothing is downloading, and don't autostart when queue was purposely paused
=> adjust so downloader doesnt autostart when queue was paused

app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/HttpPageLoader.kt
resolves #2386 
cancel queued loads when the page that requested the loads is destroyed
=> Improve Loading Speed When Skipping Pages in a Chapter

build.gradle
Was originally added in 5a3e30b30ac1290a5985441ad83ae10c80e0e1ce but is no longer needed.
=> Remove repository for Conductor snapshot

app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiApi.kt
some english katakana romaji manga title 
bangumi  tracker search api will retrun json like  {code":404,"error":"Not Found"} not a list result
@feilongfl
=> fix bangumi tracker crash in searching english manga title

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
It wasn't possible to select the 'Default' category in the categories to include in global update.
This fixes that.
=> Made 'Default' category selectable in global update settings

app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/Bangumi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiApi.kt
bangumi track will override record to 0   every track search(bind)
this update() should not be here
and
the update status api must be called before update chapter api
Need update status to "do"(reading) first , then you can update chapter num
Otherwise chapter num will uploaded next call
=> fix bangumi track will override record to 0 after every track search(bind)

app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/BaseController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/catalogue/browse/BrowseCatalogueController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/extension/ExtensionController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
tl;dr: Toolbar is hilariously broken and Idk why I'm even trying to fix this.
Basically it seems like expanding/collapse an actionView after the toolbar is already finished laying out its items (e.g. from user interaction) doesn't trigger a re-layout of its items. 
That's why in the before gif, the filter icon is both shown and in the overflow at the same time. But when navigating back to the screen (or rotating the screen), since the actionView is already expanded (in onCreateOptionsMenu) before the layout, the filter icon disappears properly.
So just invalidate the menu if opened by user and force a new layout.
Before:
After:
=> Toolbar Menu Items Fix

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt
- fix preload on last page for R2L reader
- page 3 bug: open a new chapter and scroll to page 3. Then use the scrollbar arrow to go to next chapter. The scrollbar page numbers don't update until you perform a page change.
=> Some Misc Minor Reader Bug Fixes

app/src/main/java/eu/kanade/tachiyomi/ui/base/presenter/NucleusConductorDelegate.kt
This code was sort of fine when it used raw Java types, but the Kotlin equivalent technically calls a method that takes a Nothing-typed argument with a value that is not of type Nothing. Whether that works depends on how lenient kotlinc is about inserting casts in bytecode.
The solution is to give the unknown type represented by a star an explicit name by capturing it in a type variable, then cast to that type instead of Nothing. This is guaranteed to be an unchecked, but valid, cast.
=> Do not suppress a type system error

app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
Closes #1955 and #2473.
Makes it a bit hard to tell what a card or dialog's borders are though.
=> Use black background for AMOLED theme cards, dialogs

app/src/main/AndroidManifest.xml, app/src/main/java/eu/kanade/tachiyomi/ui/main/DeepLinkActivity.kt
Fixes #2054 hopefully without breaking deep linking again.
The idea is to simply redirect all deep links through an invisible activity. This provides full control of the  intent that actually reaches the MainActivity and lets us apply the appropriate flags to ensure it launches correctly, while avoiding the `singleTask` launch mode on MainActivity to fix #2054.
Scenarios tested on Android 9:
=> Deep Link and Launch Mode Fixes

app/src/main/java/eu/kanade/tachiyomi/data/database/queries/MangaQueries.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/queries/RawQueries.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryNavigationView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySort.kt, app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterSourceSync.kt, app/src/main/res/values/strings.xml
Latest chapter is as it sounds
Last update is now any changes to the chapter list (addition, removal, rename, etc.; this is what the behavior was prior to the commits referenced in #2539)
Fixes #2539
=> Library View: Add latest chapter sorting and revert last updated sorting changes

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
_Hopefully this was the only string that dictated the default setting._
This is the recommended way of handling application theme defaults according to the Android Developers page about Dark themes.
> When running on Android 10 (API level 29) and higher, the recommended options are different, to allow the user to override the system default:
> 
> **Light**
> **Dark**
> **System default** (the recommended default option)
- https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#changing_themes_in-app
=> Change default theme to System Default

app/build.gradle, build.gradle.kts, ktlintCodeStyle.xml
Set it up to required lint before a build, and lint requires a format.
It formats files then lints.  Only thing format can't fix is imports so you manually have to fix.  Any lint errors fails the build.  So nobody can commit bad code.
I also added an intellij code style based off their recommendations.
Note  if/when you merge this you should run a make on your computer and fix the imports as it will fail the build.  Then merge in.  It basically is gonna format 90% of files in the repo.
=> add ktlint

app/src/main/java/eu/kanade/tachiyomi/data/track/TrackService.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/Bangumi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/Kitsu.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeList.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/shikimori/Shikimori.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackPresenter.kt
Fix edge case bug where status gets stuck on "complete" if the read chapters equals total chapters.
Also add support for the reverse, where a "complete" status auto sets the read chapters.
=> Minor Tracking Fixes.

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderSettingsSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonAdapter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt, app/src/main/res/layout/reader_settings_sheet.xml, app/src/main/res/values/strings.xml
As per issue https://github.com/inorichi/tachiyomi/issues/1653
The transition page will not show if the "force" setting is off and the next/previous chapter has loaded. At a normal reading pace, this should be consistently the case due to last page kicking off preload.
Transition/loading page will show regardless of the setting if the page hasn't loaded yet or failed to load.
=> Added config to hide transition page when not needed

app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/ChapterLoader.kt
Related issue: https://github.com/inorichi/tachiyomi/issues/2715
From time to time, a downloaded chapter's pages don't show up, instead
showing an infinite progress spinner with no error message or timeout. 
After reproducing said issue, the reason behind it is that `chapter.pageLoader` is `null` while the `state` is `Loaded`. PagerPageHolder simply has a stub for that case:
`val loader = page.chapter.pageLoader ?: return`
Normally this shouldn't ever happen since `state` gets set to `Wait` immediately `pageLoader` gets recycled. It might possibly be happening if pages finish loading after chapter gets recycled, for some reason, which would set the `state` to `Loaded` again (https://github.com/inorichi/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/ChapterLoad …
=> Fix for perpetually loading chapters

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
Fixes issues #2715, #2727, #2728 
1. Disable "Always show chapter transition" in settings
2. Download a regular manga, with >3 chapters and >3 pages per chapter.
3. Open a middle chapter in manga, let's call it chapter 5. Casually scroll to the next chapter.
Current chapter is now set to 6, prev is 5, next is 7.
4. Scroll one page back onto the last page.
What happens here is the following:
- We're at last page, so next chapter's (7) preload is requested. That chapter hasn't been loaded yet, so the preload begins.
- We're at different chapter than previously, so chapters get shifted. Current is now 5, previous 4, next 6.
- At the same time, since chapter 7 is not referenced anymore, it gets recycled.
- Preload of chapter 7 is finished, and its status gets set to Loaded.
5. Scroll forward …
=> Faulty preload fix

app/src/main/java/eu/kanade/tachiyomi/ui/migration/MigrationController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/migration/MigrationPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/migration/SearchController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/migration/SearchPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/migration/ViewState.kt
Moves a lot of the logic that was previously in MigrationController to migration.SearchController.
After this, we should be able to e.g. add a menu item to any given manga info view for migration, etc.
=> Make migration manga-centric rather than source-centric

app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeListInterceptor.kt
Should've been closed but still worked since old version of okhttp ignored the leaky response. Newer versions now throw an exception.
=> [MAL] close response before proceeding chain in interceptor

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonAdapter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
Fixes #2870
Reproduction:
1. Open a middle chapter of a non-downloaded manga
2. Carefully scroll up one page to the last page of the previous chapter
3. Scroll down through the chapter until next chapter
If your viewer was set to webtoon/continuous vertical, the app crashes. For pager viewer, the next chapter can't be loaded until you go back and forward again.
The reason this happens is due to a race condition caused by the edge-pages of the previous chapter (since last two pages are loaded) triggering preload of `Next` chapter, which is interpreted to be the one _after_ next. The chapter gets loaded & disposed at the same time, getting stuck in a "loaded with no loader" limbo.
The fix uses current chapter to prevent non-current pages from triggering the preload.
=> Fix for app crash #2870

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt
Kind of implements #728 but the author changed description.
This change lets you zoom out in webtoon/continuous vertical reader, which helps reading in landscape orientation.
=> Webtoon zoom out

app/build.gradle, app/src/main/java/eu/kanade/tachiyomi/util/view/ViewExtensions.kt
@Kennyc1012 has rewritten the old dead library into Kotlin (thanks!) with simplifications and some features. I hope you don't mind :) https://github.com/Kennyc1012/TextDrawable
I built an APK with the changes and couldn't find any bugs related to it, so I think it's probably good (or I'm just a terrible bug-finder).
Also bumped AndroidX Preferences 1.1.0 to 1.1.1.
=> Replace TextDrawable with a Kotlin fork

app/src/main/java/eu/kanade/tachiyomi/util/storage/EpubFile.kt
Fixes two problems I encountered trying to view local manga EPUBs in Tachiyomi:
* Image tags using relative paths were not resolved correctly.
* "META-INF/container.xml" couldn't be located in some EPUBs that used "\\" as a path separator.
=> Improvements to EPUB support.

app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt, app/src/main/java/eu/kanade/tachiyomi/util/storage/EpubFile.kt
Follow-up to my previous pull request for some additional EPUB enhancements.
Pulls the following information from the first chapter for local manga:
* Author
* Description
Pulls the following information for each chapter:
* Title
* Scanlator (Set to Publisher if found, otherwise Creator)
* Publication Date
Also contains code to fuzzy-match manga titles to remove them from chapter names, for cases in which a manga's title within chapter metadata contains characters that can't be represented in the manga directory name.
=> Pull basic manga/chapter metadata from EPUB files.

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
I noticed this when reading the diff comparison in issue #2959. I doubt this solves the issue but it was almost certainly a mistake.
=> fix copy paste mistake in PreferencesHelper.kt

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/info/MangaInfoPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/util/MangaExtensions.kt
https://github.com/inorichi/tachiyomi/issues/3139
My PR actually potentially causes this kind of issue, since even though the thumbnail url won't get set to null, the local cover file will still be deleted. And it's possible the current url is no longer valid. Added some additional logic to prevent that from happening.
Not sure what happened in the original issue though, since my PR hadn't even been merged yet. My guess it was just a networking error with fetching the new url.
=> Cover Update Followup to Address #3139

app/src/main/res/values/styles.xml
Weird how nobody's noticed this issue yet 🤔  
<details>
</details>
=> fix regular font family name

app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ChapterLoadStrategy.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryPresenter.kt, app/src/main/res/menu/chapters.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values/strings.xml
Solves #1962. Spanish `strings.xml` contains the proper translation for the new feature.
---
A few things as a first-time contributor:
- Handling masks is a real pain when it comes to adding new features. I guess this is done for performance reasons or for easier serialization, but it's actually necessary?
https://github.com/inorichi/tachiyomi/blob/8a4c4c346ab8f23fbe3e12d091ad291cbb0dcc7c/app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.kt#L58-L85
- The use of masks makes it harder to find every place that uses the sorting method, so I missed a few in my first PR.
- The sorting selection function for chapters redefines each function if the order is ascending/descending, requiring code duplication:
https://github.com/inorichi/tachiyomi/blob/cac11f8be4b67f23670bceb9f9a5326cf2 …
=> Sort chapters by upload date

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/util/MangaExtensions.kt
Closes #3168 
Fixes #2325
Also some other related changes
- Fix bug with library updates where new chapters do not download if the manga is in multiple categories and download categories are specified.
- Allow auto initial chapters fetch on `ChaptersController` when not navigating from browse source.
=> download new chapters changes

app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt, app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterSourceSync.kt
This renames downloaded chapters when the chapter names change on the source, because it is very annoying to have all of my downloads disappear as soon as volume numbers or chapter titles are added.
Addresses #1338, so long as the chapter's url stays the same.
=> Rename downloaded chapters

app/src/main/java/eu/kanade/tachiyomi/widget/preference/LoginDialogPreference.kt, app/src/main/res/layout/pref_account_login.xml, app/src/main/res/layout/track_search_dialog.xml
1. Use material password toggle icon for track login.
2. Use material for track search for enabling the clear text button. Useful for clearing out long manga names when search fails. Opted to keep the UI similar (underline only).
<details>
</details>
=> Text Input Improvements

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
ignore fact that loader might not be downloadPageLoader.
This fixes the following:
lets say i have 3 chapters, all downloaded, chapter 1 and chapter 2 are marked read.
Nth is set to keep 2nd last read.
if i click on chapter 1 read it, continue into chapter 2 and read it.  continue into chapter 3 and read it
i back out to the chapter list
chapter 1 is deleted
now lets say same scenario but instead of clicking into chapter 1 i click into chapter 3.  I read it back out to the chapter list
chapter 1 is NOT deleted
=> Nth download tweak

app/build.gradle
https://github.com/inorichi/tachiyomi/commit/cae90ddd088fbc27310a64dbcc2174d2c391f8b9 disabled Proguard due to issues with certain extensions. This was probably due to code shrinking and obfuscation. Using a post processing block, we can enable the code optimization and remove unused resources features without code shrinking/obfuscation.
Postprocessing block is described here: https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.BuildType.html#com.android.build.gradle.internal.dsl.BuildType:postprocessing
The only downside is that the postprocessing block is incubating and might be subject to future changes
=> Enable R8 code optimization

app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/sources/MigrationSourcesPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/SourceFilterController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/SourcePresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchPresenter.kt
Extensions are sorted by something like `eu.kanade.tachiyomi.extension.all.mangadex` so it's already case-insensitive, but sources sorted by it's normal name like `MangaDex` so it's case-sensitive. I just added `toLowerCase()` in few places to make sort consistent for sources and extensions. In examples you can see that `Mangabat` was below `MangaTX` but now it's above `MangaBob`.
<details>
<summary>How it was before</summary>
</details>
<details>
<summary>How it is in this PR</summary>
</details>
I did two changes in `GlobalSearchPresenter.kt`, I suppose that one is used when global search is initialized and second one to display results?
=> Change sources sort to case-insensitive

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerTransitionHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonTransitionHolder.kt, app/src/main/res/drawable/ic_warning_white_24dp.xml, app/src/main/res/drawable/ic_warning_white_48dp.xml, app/src/main/res/values/strings.xml
closes #3732 
Its add a warning on the transition page that shows how many chapters is missing if there are any chapters missing else it will not show
| If chapters are missing | If chapters are not missing | When there are no more chapters |
|-|-|-|
|  ![Screenshot_1599064808](https://user-images.githubusercontent.com/6576096/92011992-260e7300-ed4c-11ea-81d7-4975934b802f.png) | ![Screenshot_1599065385](https://user-images.githubusercontent.com/6576096/92012720-17748b80-ed4d-11ea-90ba-533d7d2c816d.png) | ![Screenshot_1599065594](https://user-images.githubusercontent.com/6576096/92013075-94a00080-ed4d-11ea-8e55-ff82a6a63d68.png) |
=> Add missing chapter warning

app/src/main/res/layout/source_filter_sheet.xml
Fixes #3854 
Padding in the bottom of the filters sheet is a bit wrong. This fixes it.
Before:
After:
=> Fix visual issue with bottom padding in filters sheet

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/more/MoreController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt, app/src/main/res/values/strings.xml
Implementing feature to turn on/off reading history of chapters
I'm not really sure where to put it (on which category of preferences), but I'm happy to help and fix any issues with this pull request.
Resolves issue #3772
=> [Feature Request] Option to turn off History - #3772

app/src/main/java/eu/kanade/tachiyomi/data/database/queries/HistoryQueries.kt, app/src/main/java/eu/kanade/tachiyomi/data/database/queries/RawQueries.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryPresenter.kt
Fixes the subscription, history now updates after changes in the db, only thing that partially doesnt work is search, it will reset to a non-searched state even when the search is in the search bar after a update. 
Because of this the deletion affects the history view even without calling updateList
Closes #3896
=> History fixes

app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChapterHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChaptersAdapter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesHolder.kt
Darkens the description color on Manga Info page as well as the Updates view.
It closely matches the color of "DOWNLOADED", although that one was not a regular android attribute so couldn't figure out how to make `getResourceColor` to work for those.
`0.62f` value wasn't gotten organically from other colors, I tried finding something similiar but I thought that (`100`-`38`=`62`), `100` being unread, `38` being read, `62` now being sub-unread.
Feel free to grill me on this one but I felt <img src="https://cdn.discordapp.com/emojis/705791131694399540.png?v=1" alt="kannaKMS" width="32" height="32"> when looking at full white both texts... <img src="https://cdn.discordapp.com/emojis/742391272865661111.png?v=1?v=1" alt="vampySmug" width="32" height="32">
| Original | Edited |
| -------- | …
=> Darken the description colors

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/MissingChapters.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ReaderTransitionView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonAdapter.kt
mhrj pointed this out on Discord, [link to message](https://discordapp.com/channels/349436576037732353/566585518171881493/764861993009676288)
| Before | After |
|---|---|
| ![Screenshot_1602430970](https://user-images.githubusercontent.com/6576096/95683064-46eaa380-0be9-11eb-9591-b7b62d45eb43.png) | ![Screenshot_1602431650](https://user-images.githubusercontent.com/6576096/95683313-c75dd400-0bea-11eb-8578-e7dd0a134f8a.png) |
I found that this chapter was recognized as 0. To fix this I added some RegEx to see if the chapter name contains any numbers.
If it doesn't contain any number it returns false. Then it uses isChapterRecognized to see if the number was recognized as a chapter number if it was not then it returns false. Else it continues with the function.
=> Fix missing chapter warning when chapter number is not recognized

app/src/main/res/layout/source_list_item.xml
Fixes #3967 
The `textSize` for `TextAppearance.Regular.SubHeading` was changed in commit a3c598a.
Since the issue only wants the title for the list item to be bigger again I only changed it to 16sp
=> Make list view font size bigger again

app/src/main/AndroidManifest.xml, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/res/values-cs/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/s_pen_actions.xml
Adds support for S Pen Air Actions for Galaxy Note 10 and newer devices. This basically allows you to use the pen to do some gestures and respond with actions - each gesture is converted to a key event that is sent to the app.
Only one activity can handle Air Actions in the app, Reader seemed the most useful to me.
All actions are configurable in the settings, the `<preference />` xml tag is only the default which can be changed by user.
If there are any other actions that you think would make sense in a reader, let me know, I can implement them.
The actions:
- **Next page** - default air action is single button press because it's probably the most used action
- **Previous page** - default air action is double button press
- **Next chapter** - default air action is swipe right
- …
=> Add support for S Pen actions

app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/SourceController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
Changes some behavior when in Incognito Mode.
Added behavior
- Does not add the source to last used when opening it
- Does not save chapter progress (overwritten if the manga is being tracked by a tracker)
For example, when opening a source to browse it that will not add it to last used. Also when reading a chapter and exiting/(reading to the last page) it will not save the progress unless it is being tracked.
=> Enhance incognito mode

LICENSE
http://www.apache.org/licenses/LICENSE-2.0 makes it pretty clear the appendix is supposed to be separate from the rest of the license. It already is in this repo, at the end of the README. I guess inorichi just forget to get rid of it at the end of LICENSES.txt, especially considering it's not filled in.
=> Remove Unfilled License Appendix From Unnecessary Spot

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/res/layout/reader_activity.xml
**What it does**
This makes the snackbar that is shown when opening the reader dismissible
**Why**
It is quite annoying waiting for it to disappear when you quickly want to jump to a specific page
=> Reader snackbar dismissible 

app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt
Browse or Library -> Global Search -> Source Search Results
1. Trigger global text search (from Browse, Library or anywhere else).
2. Press source name to view more results from that source.
3. Press back button.
Browse or Library <- Global Search <- Source Search Results
It's more natural to expect the back button in step 3 to direct user back to global search.
Browse or Library <- Global Search <- Source Page <- Source Search Results
Back button clears the search text, directing user to source's default page.
This inconveniences the user to press back twice just to go back to the global search results.
=> Direct user back to global search when coming from source search results

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderSettingsSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ViewerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt, app/src/main/res/layout/reader_pager_settings.xml, app/src/main/res/layout/reader_settings_sheet.xml, app/src/main/res/layout/reader_webtoon_settings.xml
- Adds viewer navigation settings to the actual settings page
- Split invert tapping for webtoon and pager (because one can have different navigation for webtoon and pager)
- Use `<include />` for instead of a constraint group because not being able to use `isVisible` with the latter one (also `reader_settings_sheet.xml` is already hard to work with)
=> Navigation settings and split invert tapping for webtoon and pager

app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/Kitsu.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/track/TrackLoginDialog.kt
Fixes #4324
Currently, if you input the wrong credentials when login into Kitsu (tracker) it will count as a successful login.
This is solved by removing the try/catch in `Kitsu` and handling the exception in `TrackLoginDialog` instead
=> Fix Kitsu toasting "Logged in" when there is an error

app/src/main/res/color/button_action_selector.xml, app/src/main/res/layout/chapter_download_view.xml
Anaheim pointed out on Discord that the download button uses a different color from the pin button, this fixes that
https://discord.com/channels/349436576037732353/694092459839455243/802124365524893716
Anaheim also pointed out that it probably the same case for buttons in the manga info header. But I'm unsure if they should be the same color as the download button and pin color
https://discord.com/channels/349436576037732353/694092459839455243/802133314688778280
| Before ||
|---|---|
| ![Screenshot_1611316057](https://user-images.githubusercontent.com/6576096/105487222-069ec500-5cb0-11eb-8597-7bca5d7871fa.png) | ![Screenshot_1611316063](https://user-images.githubusercontent.com/6576096/105487229-09011f00-5cb0-11eb-80dd-047645a31ab9.png) |
| Header buttons: hsl(0, 0%, 45%) <br> Download …
=> Match color for download, header, and pin buttons

app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryHolder.kt, app/src/main/res/layout/history_item.xml, app/src/main/res/layout/updates_item.xml
It has annoyed me that history uses card background while updates don't. So this makes history and update item look more the same. 
| Updates | History | [Not in PR] History but with grey tinted ImageButtons |
|---|---|---|
| ![Screenshot_1611749515](https://user-images.githubusercontent.com/6576096/105989780-e2712880-60a1-11eb-8ea1-59afba72860f.png) | ![Screenshot_1611749512](https://user-images.githubusercontent.com/6576096/105989769-e00ece80-60a1-11eb-9b41-265fe85051e3.png) | ![Screenshot_1611749488](https://user-images.githubusercontent.com/6576096/105989755-dc7b4780-60a1-11eb-9ba2-560494bad8c1.png) |
| Title is now bold | Removed card background | I thought this looks weird, that why I didn't include it. But would match ImageButton tint on other screens |
=> Unify history and update item

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderSettingsSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ViewerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt, app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt, app/src/main/res/layout/reader_settings_sheet.xml, app/src/main/res/values/strings.xml
closes #4468 
This adds another option to let users invert dual page split
This would allow users to change the placement for Webtoon and Continous Vertical as it currently places them as the user was reading R2L
=> Let users invert dual page split

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderSettingsSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ViewerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt
closes #4525
This splits dual page split setting from applying to both Paged and Webtoon at the same time. To let users control if both or just one viewer is gonna split the dual paged content
=> Dual page split allow to have different setting for Paged and Webtoon

app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
Updates to the new URL. Maybe create a Cloudflare redirect specifically for this one as well at least for a little while?
Alternatively I can create a page under that url on the website with a link to the updated url since Vuepress own Redirection tools doesn't seem to work as we want them to.
=> Update URL for Local Manga guide

app/src/main/java/eu/kanade/tachiyomi/data/database/queries/RawQueries.kt
This will prevent filtering out chapters that don't have upload date from Updates screen.
I only tested it on one manga. Not sure if it can cause some bugs that I can't think of right now.
As for sorting in the query - maybe remove it, since it's kinda redundant? Chapters are sorted on Updates screen anyway.
<details>
<summary>Example</summary>
| Updates screen | Chapter list without dates |
| --- | --- |
| ![Screenshot_1615673386](https://user-images.githubusercontent.com/65343233/111051289-a8de5c00-845a-11eb-84db-ec16c7bb3de4.png) | ![Screenshot_1615673380](https://user-images.githubusercontent.com/65343233/111051293-af6cd380-845a-11eb-949a-ecab943ab0a1.png) |
</details>
<details>
<summary>Explanation</summary>
Original explanation - …
=> Use fetch date instead of upload date when querying recent chapters

app/src/main/java/eu/kanade/tachiyomi/data/database/queries/RawQueries.kt
Alternative for #4677, as discussed on Discord. This time I kept sorting, since we need to find most recent chapters.
Tested with ~2000 chapters, it did load only part of them, and it does seem to be faster.
Closes #4673.
=> Limit query for recent chapters to 500

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderNavigationOverlayView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ViewerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsReaderController.kt, app/src/main/res/layout/reader_activity.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
This adds an in-app overlay for navigation layouts 
The current behavior is that it will show when a user opens the reader for the first time or if a user has turned on `Show navigation overlay on start`. Then when a user starts tapping or swiping it will disaper. After that it will reaper of a user changes the navigation layout to another one
---
User opens the reader for the first time or users that have turned on `Show navigation overlay on start`
https://user-images.githubusercontent.com/6576096/111871984-2e976580-898d-11eb-94c2-1bfb94ee6640.mp4
---
After the user opens the reader for the first time
https://user-images.githubusercontent.com/6576096/111871986-30612900-898d-11eb-9c31-b8fc9d200d89.mp4
=> Add navigation layout overlay

app/src/main/res/layout/reader_transition_view.xml
| Current | Fit Center (16dp) | Fit Center (18dp) |
|---|---|---|
| ![center](https://user-images.githubusercontent.com/6576096/113478718-f282fb00-948a-11eb-94a9-903af5b15aad.png) | ![fitcenter16dp](https://user-images.githubusercontent.com/6576096/113478724-f878dc00-948a-11eb-8b8f-041ca986c827.png) | ![fitcenter18dp](https://user-images.githubusercontent.com/6576096/113478747-1e05e580-948b-11eb-8ce4-475a7446b6dd.png) |
| Currently the warning icon has a weird cropping | Fixed the cropping by using `fitCenter` but with a width and height of `16dp` it felt small | So I also changed the width and height of the `ImageView` to `18dp` |
=> Remove weird cropping from icon when showing missing chapter warning

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
Currently snackbar displaying reading direction covers the navbar, so the user can't immediately see how many pages does a chapter have, nor can he scroll fast without dismissing the snackbar or waiting for it to disappear. This commit replaces a snackbar with centered toast
=> Replace reading mode snackbar with toast

app/build.gradle.kts, app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/sources/MigrationSourcesController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/SourceController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsController.kt, app/src/main/res/values-v23/themes.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml
Insets are handled by [Insetter](https://chrisbanes.github.io/insetter/) so it should be consistent across APIs.
The navigation bar color will only be set transparent when it's positioned on the bottom (e.g., on landscape orientation with non-gesture navbar won't be set transparent).
[portrait](https://user-images.githubusercontent.com/12537387/114224914-e7a0fc80-999b-11eb-9987-8d6b36f24885.png)
[landscape gesture 1](https://user-images.githubusercontent.com/12537387/114224630-8547fc00-999b-11eb-88d6-e9114bf64efd.png)
[landscape gesture 2](https://user-images.githubusercontent.com/12537387/114224754-b0325000-999b-11eb-88f5-73b73ac36fc5.png)
[landscape 3-button 1](https://user-images.githubusercontent.com/12537387/114224820-c5a77a00-999b-11eb-841e-3ab1617a5a24.png)
[landscape 3-button …
=> Draw edge-to-edge

app/src/test/java/eu/kanade/tachiyomi/data/library/LibraryUpdateServiceTest.kt
Wanted to inspect the project with SonarQube locally, but `./gradlew sonarqube ...` build failed. This fixed it.
=> Fix LibraryUpdateServiceTest so `./gradlew sonarqube ...` doesn't crash

app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt, app/src/main/java/eu/kanade/tachiyomi/util/system/InternalResourceHelper.kt, app/src/main/res/layout/main_activity.xml, app/src/main/res/values/themes.xml
This checks for a internal flag `config_navBarNeedsScrim` added since API 29. It exists in pretty much all of my test devices (Pixel 3, Xperia 5II and Galaxy A50).
If the flag explicitly set to false, navbar color will be set to transparent, else it will use 70% of navigationBarColor.
=> Add navigation bar scrim

app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChapterDownloadView.kt, app/src/main/res/drawable/ic_error_outline_24dp.xml, app/src/main/res/layout/chapter_download_view.xml
Replaced the indeterminable progress indicator with blinking download icon for queued items as it looks chaotic since it's impossible to sync the indicator animation.
[Before](https://user-images.githubusercontent.com/12537387/115992762-8e6ed500-a5f9-11eb-89f8-c9bd2b7275cc.mp4)
[After](https://user-images.githubusercontent.com/12537387/115992822-cf66e980-a5f9-11eb-9a97-bbf3b11763a5.mp4)
=> Make the download progress status smoother

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt
This is a cleanup of the dual page split logic and also changes so it processes the stream in the same place like J2K.
I have not noticed a performance benefit with this when using dual page split it is basically the same, but I have noticed a performance benefit if we do something like my stencil page idea in #4791 it will be a lot smoother if it processes the stream on IO rather than the main thread
=> Cleanup dual page split

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt
fixes #4982
Have tested with the chapters provided in the issue. Did make a local version of the chapters provided to see if it was caused at other positions as well. Did also test with a chapter only containing dual page spreads. And everything seems to work as intended now.
Webtoon dual-page split doesn't have this issue due to it not inserting another page into the RecyclerView
=> Fix bugs in dual-page split

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
closes #584
This adds J2K implementation of automatic background color, which was the more preferable implementation https://github.com/tachiyomiorg/tachiyomi/issues/584#issuecomment-827070474
The implementation differs a little bit like it doesn't have J2K feature `Smart (by theme)`. Changed many of the `getPixel` function calls to be in variables instead. Also tweaked the code a little bit but it works the same way.
WebtoonViewer will see that `Automatic` is selected but it will use `Black`
**WARNING: THE VIDEO CONTAINS SOME NSFW CONTENT**
https://user-images.githubusercontent.com/6576096/116786783-d7fb6c00-aaa0-11eb-9d8b-9821799fc550.mp4
^Left is Tachiyomi and right is J2K, using the same implementation
=> Automatic background color for PagerViewer

app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionHolder.kt
This PR addresses a small, purely visual issue in the extension browser that due to the ordering of the statements in a "when" clause in ExtensionHolder.kt, an unofficial extension's label will read "OBSOLETE", when it should read "UNOFFICIAL"
Before:
After:
=> Fix unofficial extensions being labeled as "Obsolete" instead of "Unofficial"

app/build.gradle.kts, app/proguard-android-optimize.txt, app/proguard-rules.pro
These are month old stats but it should be similar.
According to APK analyzer
Before: 18044 classes with 113387 methods in 3 dex files
After: 12604 classes with 68010 methods in 2 dex files
APK download size is reduced by 2.8 MB
And I believe this should also be enabled on preview builds, but it uses debug build type so we can either make a new build type for previews with R8 enabled or a separate debug build type with R8 disabled.
=> Reinstate Proguard/R8

app/src/main/res/layout/common_tabbed_sheet.xml, app/src/main/res/layout/main_activity.xml, app/src/main/res/layout/main_activity_toolbar.xml
Does what Google apps does, uses the colored ripple for Tabs as well and not just bottom nav.
| New | Old |
| ![new](https://user-images.githubusercontent.com/10836780/119239708-1c7fa200-bb4b-11eb-9157-eadab2159d25.png) | ![old](https://user-images.githubusercontent.com/10836780/119239785-9fa0f800-bb4b-11eb-8f9f-b2df03edd59b.png) |
=> Matches tab ripple color with bottom nav

app/src/main/res/drawable/ripple_background.xml, app/src/main/res/drawable/ripple_light.xml, app/src/main/res/layout/common_tabbed_sheet.xml, app/src/main/res/layout/main_activity.xml, app/src/main/res/layout/main_activity_toolbar.xml, app/src/main/res/layout/manga_info_header.xml, app/src/main/res/layout/pref_about_links.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
- Added override for `rippleNavColor` for the Dark Blue and Light Blue themes, now doesn't blend in.
- Fixed so background for Settings used background color, meaning it fixes AMOLED.
- About icons now uses Ripples too, since it was added to the main Style instead.
=> Ripples patch

app/src/main/res/layout-sw600dp/main_activity.xml, app/src/main/res/layout/main_activity.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
Creates a Toolbar variable for ripples so themes using a custom toolbar color (Like, Dark blue and Light blue) can have more distinct ripples.
Renames the rippleNavColor to rippleSecondaryColor as it's not just for navigation anymore.
Adds rippleSecondaryColor for some text buttons:
| New | Old |
| ----- | ----- |
| ![New](https://user-images.githubusercontent.com/10836780/119271444-d46f8680-bc01-11eb-91b2-64d9e86448ef.png) | ![Old](https://user-images.githubusercontent.com/10836780/119271440-d20d2c80-bc01-11eb-8aea-6c22ab5fbc9d.png) |
=> Create a toolbar variable for ripples

app/src/main/java/eu/kanade/tachiyomi/App.kt, app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
The application class onCreate will also be called when user navigates to an
activity after the app process is killed by the system.
So make sure the incognito is disabled only when the entry point of the app is
created from scratch (e.g. after being force closed by the user).
=> Fix incognito mode disabled after the app kicked out of memory

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt, app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
This ports **Midnight Dusk** and **Hot Pink**  from TachiyomiSY.
My first commit reorganizes and structures the theme file differently to make it easier to follow, edit, and replicate. 
That commit itself probably makes reviewing harder, not sure if there's a way to filter out that during review.
As AMOLED now gets a child theme I decided to make it a Base style of its own, instead of following the Dark themes.
- AMOLED ripple changed from 6% opacity to 8% opacity.
- Added a AMOLED specific stuff now that it's not inheriting from Dark. (`Toolbar`/`AlertDialog`/`Colors`)
@CrepeTF added the item `background` to each theme when he added **Midnight Dusk**, he could not remember why but it might be safe to leave it in?
I switched place between **Light reader** and **Dark reader** while …
=> Add "Midnight Dusk" and "Hot Pink" themes

app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt, app/src/main/java/eu/kanade/tachiyomi/network/RateLimitInterceptor.kt, app/src/main/java/eu/kanade/tachiyomi/network/SpecificHostRateLimitInterceptor.kt
I pulled the rate limit interceptors from the extensions repo. Apply a rate limit to anilist, current limit is 90 per minute, so i'm using a bit of a buffer with 85, just in case.
=> Rate limiting for AniList tracker updates

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt, app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
I thought that light users deserve some love too as they're practically forced to only use the default theme.
As for the name, the only matching thing I could think of was this 🍓🍸
Just unfortunate that the Unread/Download badges color can't be set from the theme as it's forced right now.
I will now work on finishing the animations PR.
| Screenshot |
| ------------ |
| ![Strawberry daiquiri](https://user-images.githubusercontent.com/10836780/119393020-c2a8e480-bcd0-11eb-84fc-115791666248.png) |
=> Added "Strawberry Daiquiri" theme

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsLibraryController.kt, app/src/main/res/values/strings.xml
This adds a new preference in the Library screen to enable trackers update during Library update. It defaults to off. Should probably be merged after #5163 to avoid issues with AniList.
=> Background tracker update during Library update

app/src/main/res/values/themes.xml
It feels odd enough that having Gray theme isn't respected in the in-reader settings sheet. I get that it follows the background set to the manga but this isn't true for the Gray background option. I can't fix so it all follows theme unfortunatelt but I can fix this.
| Full Grey (new) | Grey and AMOLED (old) |
| ---------------- | --------------------------- |
| ![new](https://user-images.githubusercontent.com/10836780/119533482-2b05cd80-bd86-11eb-924c-22b1f53b5a40.png) | ![old](https://user-images.githubusercontent.com/10836780/119533817-8a63dd80-bd86-11eb-9e7d-c361a5e3d1f4.png) |
=> Set grey setting sheet for Grey background option

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsLibraryController.kt, app/src/main/res/values/strings.xml
Closes #4957
I also pulled the `wifi` and `ac` strings into constants.
=> Display the currently active restrictions in the library update preference

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryComfortableGridHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCompactGridHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryItem.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryListHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt, app/src/main/res/values/strings.xml
This PR adds a checkbox to the Library settings sheet underneath the "Unread" and "Download" badge display options to allow hiding the green "Local" tag on library manga.
This PR closes #5018
=> Added ability to hide "Local" tag from library manga.

app/src/main/java/eu/kanade/tachiyomi/ui/manga/chapter/ChapterDownloadView.kt, app/src/main/res/layout/chapter_download_view.xml, app/src/main/res/layout/chapters_item.xml
* Remove the blinking icon and add back the indeterminate indicator for queued items
* Make the downloading indicator a solid circle
[Preview](https://user-images.githubusercontent.com/12537387/119855198-e885f180-bf3b-11eb-8688-49971fad477d.mp4)
=> Adjust chapter download button visual

app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/SourceSearchController.kt
apparently was added to Sy in https://github.com/jobobby04/TachiyomiSY/commit/8686fecb1fe0f436e503f005de3e6218fe8f76d5
added it for main as well
Co-Authored-By: jobobby04 <jobobby04@users.noreply.github.com>
fixes https://github.com/tachiyomiorg/tachiyomi/issues/5027
=> Add long click to view manga in Migration Source Search

app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
Closes #5249 by adding a check that the backstack size is 1 before opening the Download Queue
=> Fix Download Queue opening multiple times from rapidly clicking Updates (#5249)

app/src/main/java/eu/kanade/tachiyomi/data/database/models/Category.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceKeys.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt, app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryItem.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsLibraryController.kt, app/src/main/res/layout/library_list_recycler.xml, app/src/main/res/values/strings.xml
Supersedes #3319
https://user-images.githubusercontent.com/6576096/120068358-913d6980-c080-11eb-976e-ad88baf47e30.mp4
The default category uses the preference, `preferences.libraryDisplayMode()`, instead of the flags because it will insert it into the database otherwise
=> Added category-wise display setting

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
This closes #5288 by disabling and setting the opacity of the arrow image on the prev / next chapter buttons in the Reader to 1/4 opacity (to dim it) if there is no next or previous chapter respectively.
For manga that have a single chapter, I included the feature that both the "previous" and "next" chapter buttons will be hidden, which has the beneficial side-effect of allowing the page seek-bar to expand to take up the space.
I included this feature as I believe it would be an additional improvement to the reader (and it is implemented in the same Tachiyomi function), however if it is preferred, I could move that feature to a different PR or just nix it entirely.
Disabling next chapter button if no chapter:
Hiding both previous and next chapter buttons for single chapter manga:
=> Added chapter-contextual disabling / hiding of reader prev/next buttons

app/src/main/res/layout/history_item.xml
It felt unnatural tapping a history item and it not giving any kind of feedback of being pressed.
- Replaces `margin` with `padding`.
- Adds the `selectableItemBackground` tweaked ripple drawable.
- Changes `height` to match the `padding` so the layout remains exactly the same.
| New (tap/hold) | Old (tap/hold) |
| ![New](https://user-images.githubusercontent.com/10836780/121094798-7b9e1180-c7ef-11eb-8118-613a78717528.png) | ![Old](https://user-images.githubusercontent.com/10836780/121094809-7f319880-c7ef-11eb-912d-b6da40c52e24.png) |
=> Add ripple to history items

app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
get() throws an error on an emptyList. this checks if the category list is empty and uses the normal settingsSheet?.show() method if it is.
=> Fix library settings sheet causing app to crash when the category list is empty

app/src/main/res/color/selector_overlay.xml, app/src/main/res/drawable/library_item_selector.xml, app/src/main/res/drawable/library_item_selector_overlay.xml, app/src/main/res/layout/source_comfortable_grid_item.xml, app/src/main/res/layout/source_compact_grid_item.xml, app/src/main/res/values/dimens.xml
Adding a colored overlay as suggested to me by @CarlosEsco.
This also fixes the selector corner radius so it looks even, guided by [this article](https://webdesign.tutsplus.com/tutorials/quick-tip-rounded-corners-done-right--webdesign-7127) sent by @vengiare.
- **Android 10** with **Huawei Mate 20 Pro**.
- All themes except legacy blue (follows base blue).
- Portrait and landscape.
- `3`, and `6` items per row.
https://user-images.githubusercontent.com/10836780/121623119-6fc08280-ca6f-11eb-99d4-ecfc281cc1d6.mp4
| New | Old |
| ![New](https://user-images.githubusercontent.com/10836780/121623464-068d3f00-ca70-11eb-9195-50ada0df5c66.png) | ![Old](https://user-images.githubusercontent.com/10836780/121623470-09882f80-ca70-11eb- …
=> Improvements to the new library item selectors

app/src/main/java/eu/kanade/tachiyomi/ui/library/ChangeMangaCategoriesDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt, app/src/main/res/values/strings.xml
Currently (as of 0.11.1), if a user long clicks manga in their library, and hits the category button on the action bar, but they don't have any categories setup: they will be met with a "Set Categories" dialog that has no content, a cancel button, and an OK button. I'm certain this could be a source of confusion for new users
This PR modifies the ChangeMangaCategoriesDialog to present the user with the text: 
> You have no categories. Go to \"More\" > \"Categories\" to create them
and only an OK button if the dialog is invoked with an empty category list. (As far as I can tell, the Library is the only place where this dialog can be invoked with an empty category list)
=> Added text to category changing dialog when shown with no categories

app/src/main/res/drawable/ic_delete_sweep_24dp.xml, app/src/main/res/menu/history.xml
Places it as its own icon, having an overflow with only one item doesn't make much sense when that's not the behavior in other parts of the app.
First I thought it might potentially be destructive to have it so open, but:
- There is a prompt telling the user exactly what will happen.
- If the user is... skilled enough to dodge the prompt and delete it anyways, backups should contain that information too.
- If the user does not have a backup with it either, the next Darwin awards are probably not too far out and hopefully the user is taught a valuable lesson.
- **Android 10** with **Huawei Mate 20 Pro**.
| New | Old |
| ![New](https://user-images.githubusercontent.com/10836780/121829504-046eee80-ccc3-11eb-96b8-87e5e2659fca.png) | …
=> Move "Clear history" out from overflow

app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt
null safe cast to TextView because when searching for manga in a source,
the toolbar has no children and
find() returns null.
=> Fix crash when opening the MangaController from the browse search

app/src/main/res/values/themes.xml
This PR styles the progress dialog that appears when clicking the previous or next chapter buttons to use a style matching the current reader theme, and is more Tachiyomi-styled.
White | Gray, Black, Automatic
-------|-------------
White | Gray | Black, Automatic
-------|-------|-------
=> Apply reader theme to reader progress dialog

app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/SourceComfortableGridHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/SourceGridHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/SourceListHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchCardHolder.kt, app/src/main/res/layout/global_search_controller_card_item.xml, app/src/main/res/layout/source_comfortable_grid_item.xml, app/src/main/res/layout/source_compact_grid_item.xml, app/src/main/res/layout/source_list_item.xml
Inspired by TachiJ2K where the favorite status is more than just a lower cover alpha.
- `Browse`/`Latest` with all reading modes.
- `Global search` and `Migrate`.
- `Portrait` and `Landscape`.
- Base themes.
| New browse (Compact) | Old browse (Compact) | 
| -------------------------- | ------------------------- |
| ![New browse (Compact)](https://user-images.githubusercontent.com/10836780/122912709-ea837a80-d358-11eb-8bc4-4ac0dafa687a.png) | ![Old browse (Compact)](https://user-images.githubusercontent.com/10836780/122912722-eeaf9800-d358-11eb-9545-9511f28aa18b.png) |
| New browse (List) | Old browse (List) | 
| -------------------- | ------------------ |
| ![New browse (List)](https://user-images.githubusercontent.com/10836780/122912930- …
=> Add favorited badge to browse and search

app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryItem.kt
This PR adds an option search in library using -source 
i.e. search for all manga *not* in a particular source  
A problem when you directly add a negation check is that although
it is working, the genre search kicks in to add back every manga since
-<source> returns true for containsGenre()
Solution chosen was to check source search first, and then if it fails
move to genre check. 
In addition, now you're able to search like this:
Eg: 
1. -isekai, fantasy, -local, komga
2. -manganato, -mangakakalot, -local
Checked in following devices:
- Pixel 3 (blueline)
- Redmi 7 (onclite)
Closes https://github.com/tachiyomiorg/tachiyomi/issues/4846
_______________________________________________________
This was already present in Sy however it heavily relied to methods
defined in exh. This PR tries …
=> Extend library search by adding -<source> option

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/report_issue.yml, .github/ISSUE_TEMPLATE/request_feature.yml
Created in tandem with tachiyomiorg/tachiyomi-extensions#7914
- Renames the issue form templates to match the extensions repo ones.
- Changes the website icon as it was the same used for the **Source requests** in the extensions repo.
- Better description for the website extensions link.
- Removed ending period to match the issue templates.
- Renames "Bug report" to "Issue report", matches the extensions repo.
- Issue can be both bugs and annoyances, not just one or the other.
=> Create parity with extension repo issues

.github/ISSUE_TEMPLATE/config.yml
since it says "List of all available extensions with download links", this link to website would be more appropriate
=> fix link to List of Extensions

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
The newly added option to save pages to separate subfolders based on manga title didn't sanitize the manga title in the subfolders' names, which made it impossible to save pages from manga with reserved characters in their titles with the option enabled. This commit aims to fix that by using `DiskUtil.buildValidFilename` to sanitize it.
Side note: Kotlin and pull requests are both things I've never done before so I really hope I didn't mess anything up with this small change. I've tested it in Android Studio's emulator and it worked as expected.
=> Sanitize manga title in page download subfolder name

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
The parallel library updates I use in SY. It is parallel by source, so 5 sources can be updated in parallel. It uses a Semaphore to control when each source can start updating.
Closes #4103
=> Parallel library update

app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
When all manga are in a category that isn't the default category, the title just shows the number of items in the default category. This fixes that.
The next comment shows how to reproduce
=> Show correct number of items in the library title

app/src/main/java/eu/kanade/tachiyomi/App.kt, app/src/main/java/eu/kanade/tachiyomi/data/coil/TachiyomiImageDecoder.kt, app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
This will use reader's image decoder to decode cover images if its format is unsupported by the system. Note that currently there is no optimizations when TachiyomiImageDecoder is used so it might be problematic on larger images.
Resolves #5451
Resolves #5522
=> Support more image formats for covers

app/src/main/res/values-night/themes.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml
Resolves some of the issues mentioned in #5506
Not the same kind of Green color anymore, but it looks good? Contrast at least isn't shit
- **Green Apple** in both light and dark modes.
| New | Old |
| ![New](https://user-images.githubusercontent.com/10836780/125193411-9c251580-e24c-11eb-90ba-c7f489ad6346.png) | ![Old](https://user-images.githubusercontent.com/10836780/125193414-9e876f80-e24c-11eb-835b-a4f135a718a9.png) |
=> Improve Green Apple color in Light mode

app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/themes.xml
Resolves some of the issues mentioned in #5506
Yin & Yang theme got its chip color sets seperately (and approved by creator) as it didn't look as good following the regular automatic styling.
- All themes.
Compared using the Yotsuba  theme, which was one of the low contrast ones.
| New (Light) | Old (Light) |
| ------------- | ----------- |
| ![New 1](https://user-images.githubusercontent.com/10836780/125191846-d985a500-e244-11eb-903c-c2e1e7f0005b.png) | ![Old 1](https://user-images.githubusercontent.com/10836780/125191851-dd192c00-e244-11eb-85f6-1c5dfade52b4.png) |
| New (Dark) | Old (Dark) |
| ------------- | ----------- |
| ![New 2](https://user-images.githubusercontent.com/10836780/125191881-f02bfc00-e244-11eb-8803-672f3dc8ea5c.png) | …
=> Tweak chip contrast

app/src/main/res/values/themes.xml
refresh arrow color didnt change in dark mode
previously only look like white circle
=> fix yin & yang theme

app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt
This PR hides the Start/Resume FAB when viewing Manga info and chapters, and only shows it if there are unread chapters for the manga.
This addresses the fact that while the chapter list is loading, or when all chapters are read, the FAB is unneeded and does nothing (besides showing a Toast that there's no next chapters), as well as being slightly misleading with it's label. (Such as showing "Start" when there are no chapters, or "Resume" when there's currently no more chapters to read).
=> Hide Start/Resume FAB unless there are unread chapters and during loading

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt, app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
1. Make it easier to differentiate Manga Titles.
2.  Don't include updating manga to progress counter.
=> Update Libary update notification.

app/src/main/res/layout-sw720dp/main_activity.xml, app/src/main/res/layout/main_activity.xml, app/src/main/res/layout/main_activity_toolbar.xml, app/src/main/res/values-night/colors.xml, app/src/main/res/values/attrs.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml
Looks better than the odd forced gray used for all themes
- All themes in **Light**, **Dark** and **AMOLED** modes.
=> Make incognito bar use primary colors

app/src/main/java/eu/kanade/tachiyomi/data/track/TrackService.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/Anilist.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/Bangumi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/Kitsu.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/komga/Komga.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeList.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/shikimori/Shikimori.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
closes #200
This makes so tracking status changes depending on if a user has read chapter(s) for a manga when adding a new tracker to it.
- If a user hasn't read any it will make the tracking status plan to read
- If a user read one or more it will make the tracking status reading
- When a user changes chapter number from 0 it will change tracking status to reading
- It will not change when changing between e.g. 5 -> 10 or 41 -> 10
When a user reads a chapter it will also change to status to reading
For trackers that have rereading as status, it will leave it as is
=> Make default tracking status depend if the user has read chapter or not

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/SourceController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryCategoryView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesController.kt, app/src/main/java/eu/kanade/tachiyomi/util/view/ViewExtensions.kt, app/src/main/res/drawable/ic_tachi_splash.xml, app/src/main/res/values/themes.xml
This also adds splash screen exit animation on older android version which replicates the animation in Android 12 (I've tried).
The splash screen will be removed after all items inside starting screen is finished showing, also has timeout just in case.
=Previews=
[Android 10](https://user-images.githubusercontent.com/12537387/126042351-bfeaf480-98a2-456e-9a7b-93a8f68cd329.mp4)
[Android 12](https://user-images.githubusercontent.com/12537387/126042456-8e594109-d785-4f4e-a977-f5256c5eecef.mp4)
=> Fix splash screen icon on Android 12

app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt, app/src/main/java/eu/kanade/tachiyomi/ui/base/activity/BaseThemedActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt, app/src/main/res/color-night-v31/text_primary_monet.xml, app/src/main/res/color-night-v31/text_secondary_monet.xml, app/src/main/res/color-v31/ripple_colored_monet.xml, app/src/main/res/color-v31/text_primary_monet.xml, app/src/main/res/color-v31/text_secondary_monet.xml, app/src/main/res/values-night/colors.xml, app/src/main/res/values-v31/themes.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
Followed AOSP's DeviceDefault theme except on surface color because it breaks all dialogs.
| Light | Dark |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/12537387/126055114-3bc66445-57f4-4475-befd-6c43899c81eb.png) | ![image](https://user-images.githubusercontent.com/12537387/126055132-c17a7f12-dad7-499e-be13-fb51e8604472.png) |
| ![image](https://user-images.githubusercontent.com/12537387/126055084-62e189e0-0277-4a3f-a7f9-72a5cb0ba8b8.png) | ![image](https://user-images.githubusercontent.com/12537387/126055075-34c16cbe-48fa-4869-ba39-fe48e0aa3f76.png) |
| ![image](https://user-images.githubusercontent.com/12537387/126055162-49058687-5a05-4fbd-895a-75d25495a834.png) | ![image](https://user-images.githubusercontent.com/12537387/126055155-c18f4666-263 …
=> Add Dynamic theme for Android 12

app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
No need to touch light system bars when running the splash screen since
they're not that noticeable, and it also breaks on some ROMs.
=> Fix light navigation bar not applied on first launch

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
Format is e.g.
```
! Error 1
- Manga 1
! Error 2
- Manga 5
- Manga 2
- Manga 3
- Manga 4
```
=> For library update error log, group errors by error string, and then sort the resulting list by source

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt, app/src/main/java/eu/kanade/tachiyomi/source/SourceManager.kt
Followup to #5586
Uses "Source not found" string for failedUpdates list.
Exception behaves as normal for other cases.
=> Group 'Source not installed' cases in library update error log

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
closes #3411
This makes so the reader menu auto hides when changing page or scrolling to keep the user immersed in reading
=> Auto hide reader menu when user starts reading again

app/src/main/java/eu/kanade/tachiyomi/data/database/models/Manga.kt, app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterSourceSync.kt
last_update is used for 2 things: "Last checked" sort, and "Latest first" update order.
Prior to next_update's impl, last_update recorded the last time the given manga's chapter list changed in any way (an "update" was an addition, removal, or rename/other change in the chapter list).
When #5436 next_update was implemented, last_update's behavior was changed to instead be whatever the latest chapter upload date was, which technically fits use case 2 ("Latest first" update order) but does not at all match use case 1 ("Last checked" sort).
The next_update impl itself makes no use of last_update, so this is reverting that behavior change.
Moving forward, it may be worth renaming this field to last_change to reflect what it does. Moreover, any new field for 'latest chapter upload date' would …
=> Revert changes to last_update behavior from #5436

app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSearchDialog.kt, app/src/main/res/layout/track_search_dialog.xml, app/src/main/res/values/strings.xml
If wanting to add a manga to a tracker and it showing only one result, users thought it might automatically select this item. The tick will now appear after selecting an item:
- not having an item selected doesn't show the tick
- selecting an item enables tick
=> Tracking: replace tick with button

app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
Currently when updating the library and one has per category display setting enabled it causes scroll lag due to the adapter being reattached.
To fix this a delay is used instead of updating it when the database changes, only when per category display setting is enabled. By delaying the reattach when the display setting gets changed it does not cause the weird behavior fixed by #5640
https://user-images.githubusercontent.com/6576096/134382158-22c28979-e44b-4d28-b437-7a4ac558f3bb.mp4 
https://user-images.githubusercontent.com/6576096/134382179-f1481936-7618-40aa-8676-873715c0099e.mp4
=> Reattach after slight delay instead on every database update

app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
getCoverFile only returns a cover if it already exists, meaning
the block of code to write it from the inputstream never executes.
If getCoverFile returns null, then use previous behaviour of setting
it to cover.jpg so that if the file doesn't exist it's created
=> Fix storing covers for local manga

app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt
fixes #6022
When changing the cover of a local manga, the app crashes and the cover doesn't actually change.
This fixes it by ~reverting a probably accidental exclamation point that got introduced in f0a5557e603e31a53117c40426237d2340142bc2 and~ updating the cover cache so the MangaFullCoverDialog doesn't try to load a recycled image.
=> Fix local source cover changing

app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt, app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt, app/src/main/java/eu/kanade/tachiyomi/data/notification/NotificationReceiver.kt, app/src/main/res/drawable/ic_download_24dp.xml
Closes #2986
This PR is for the ability to download chapters through the **New Chapters Notification** actions and not having to open the app or go to the _Manga Screen_. 
- The download button will not appear for new chapters with count greater than 15 (set in `Downloader.CHAPTERS_PER_SOURCE_QUEUE_WARNING_THRESHOLD`) to minimize mass downloads
When I get notifications for new chapters while reading a **manga/manhwa/manhua** and want to download the new chapter(s), I have to close the _Reader_ and go to the manga's screen to download the new chapters.
Having to close the _Reader_ to download the new chapter(s) is especially annoying with **manhwas/manhuas** because those usually have mega tall aspect ratios per page and coming back to the chapter resets the Reader to the top of the …
=> Add download action to New Chapters Notification

app/src/main/java/eu/kanade/tachiyomi/data/backup/full/FullBackupManager.kt
Fixes #6424
Reappear stably on the api30 Android Studio Emulator,
first save a large backup file,
then save a small backup file, overwriting the previous larger backup file,
so you get a backup file with a larger size but only the first part is meaningful,
=> Fix corrupted backup file, fix #6424

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/navigation/DisabledNavigation.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerConfig.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonConfig.kt, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml
I added a navigation layout "Disabled" that doesn't contain any regions.
In many popular vertical reading apps like Naver Webtoon, navigation is entirely done by scrolling.
Users who are accustomed to such navigation system might get some unintentional page movements with current layouts, so I am proposing to add this option.
Closes #4820
=> Add option to disable navigation layout

app/src/main/java/eu/kanade/presentation/history/HistoryScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt
Makes the whole item the resume button, and you press the cover to get to manga info
| Before | After |
| ------- | ------- |
| ![crinj old item with resume button](https://user-images.githubusercontent.com/70870719/164559173-c0ac62b5-8537-4678-8947-23f94b35f15a.png) | ![chad no dumb play button](https://user-images.githubusercontent.com/70870719/164558916-eebee309-e844-49d8-a77b-e6c50873a141.png) |
=> Remove resume button pr

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt, app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferenceValues.kt, app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsLibraryController.kt, app/src/main/res/values/strings.xml
Fixes automatic library updates ignoring network constraint and closes #7016 .
Note: I've added a constraint for unmetered network to the work request. That way, the job will run as soon as a unmetered (== wifi) connection is available instead of waiting for the next run in however many hours the user set it to.
=> Fix global update ignoring network constraint

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, build.gradle.kts
Closes  #7940 
This fixed the issue of multiple bottom sheets stacking up, by adding a conditional check. 
https://user-images.githubusercontent.com/55742309/189731367-b329ac11-3603-4e8a-9b1b-9b7d9973370b.mp4
In Fix:
- Bottom sheet is being opened depending on status whether dialog sheet  is currently showing or not.
- If dialog sheet is opened once, code for opening dialog sheet won't be executed unless the user closes the  opened bottom sheet first.
=> Fix stacking of Settings menu in the reader on multiple taps

app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt, app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreen.kt, i18n/src/main/res/values/strings.xml
Implements #8382 
Clicking on individual genre chip will open pop up menu which will allow user to search genre (global or library) and copy tags to clipboard.
=> Add copy tags to clipboard feature

app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceScreenModel.kt
during browsing of a source, after finishing the query for list of mangas for a given page
the networkToLocalManga is essentially called one by one (serially),
and only after that getManga.subscribe creates flow for each manga
the problem is that networkToLocalManga is relatively slow when inserting into database,
consequently only after all entries are committed into DB (slow) and flows are created (fast)
the new page can be requested
with this change the flow for each manga is created right after the list is loaded,
such that networkToLocalManga, filtering and initializeManga happen inside individual flows,
this allows much faster response to user actions (e.g. when reaching the end of current page,
new page is requested much faster, also each flow can be cancelled when out of view of …
=> BrowseSource: do networkToLocal and initializeManga inside flow

presentation-core/src/main/java/tachiyomi/presentation/core/screens/EmptyScreen.kt
Fixes #9281
Was able to reproduce this issue on my device only after adding some extra 'w' to UI string. 
| after | before |
| ------- | ------- |
| ![after](https://user-images.githubusercontent.com/123292609/231961616-ca2feca0-9c58-4aea-bcd4-ada2cf556e13.jpg) | ![before](https://user-images.githubusercontent.com/123292609/231961631-62d00020-777b-4bec-be9c-dd30a14aed2a.jpg) |
=> Remove horizontal padding of actions row in empty screen

app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt, i18n/src/main/res/values/strings.xml
fix #8810 
Summary :
I changed the directory name when we download a manga which chapters name only composed of numbers or spaces.
It will appear like "Chapter 5" instead of "5" in the download directory.
=> Fallback chapter name if it ends up as blank

gradle/kotlinx.versions.toml
Fixes the issue were characters between `0xE000` and `0xFFFD` that are part of a valid surrogate pair got replaced with `NULL`.
=> bump xmlutil

app/src/main/java/eu/kanade/domain/manga/model/Manga.kt, core-metadata/src/main/java/tachiyomi/core/metadata/comicinfo/ComicInfo.kt
Populate the Number field of ComicInfo files with chapter numbers.  
According to the [Official ComicInfo documentation](https://anansi-project.github.io/docs/comicinfo/documentation), [Kavita's documentation](https://wiki.kavitareader.com/en/archive/guides/metadata) and [Komga's documentation](https://komga.org/guides/scan-analysis-refresh.html#import-metadata-for-cbr-cbz-containing-a-comicinfo-xml-file) (only tested with Komga)
=> Populate the ComicInfo Number field with chapter numbers

app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
- Refactor `updateSuccessState`
- Convert to `inline` function
- Use `when` for type safety if we add other `MangaScreenState` types
- Replace equivalent expressions with `updateSuccessState`
- Replace safe cast in `MangaScreen`
=> Cleanup MangaScreenModel successState usage

app/src/main/java/eu/kanade/domain/manga/model/Manga.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt, core-metadata/src/main/java/tachiyomi/core/metadata/comicinfo/ComicInfo.kt
1. Changed the serialized chapter numbers to not use decimal points if possible.
2. Add the library categories to the Manga genres with 🔰 as a prefix. 
Example output:
=> Better handle decimal chapter numbers and add categories in ComicInfo.xml files

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonFrame.kt
Translates any motion events outside the Webtoon Recyclerview to be within it. 
This also allows for scrolling and gestures like double click to zoom when touching the background (when zoomed out), like the paged vertical reader.
Closes https://github.com/tachiyomiorg/tachiyomi/issues/3127
=> Fixed scrolling on the background using long strip

app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
Closes #9577
The problem is that the queued chapters don't get updated visually until one chapter finishes downloading.
From my understanding, the issue is caused because the chapters aren't reloaded until the downlodcache issues changes, which is when the download finishes for a chapter.
Adding a subscribtion to the downloadmanager's queue state fixes the issue.
=> Fix to multiple chapter download incorrect state

app/src/main/java/eu/kanade/presentation/browse/GlobalSearchScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchScreenModel.kt, i18n/src/main/res/values/strings.xml
Related issue #6654
Added a few filter chips to the global search to quickly filter the results
- **All** : Shows all sources
- **Pinned**: Shows only pinned sources
- **available**: Hides sources that have an error (Failed to bypass cloudflare ...) 
For the implementation process I used Filterchips so I followed the way it was used in the `BrowseSourceScreen` class.
But I'm unsure if this is the best way to create the filters (using an enum)
Also for the 'available' icon I'm not sure what icon to use.
| All | Pinned | Available |
| ------- | ------- |  ------- |
| ![all](https://github.com/tachiyomiorg/tachiyomi/assets/46049558/d74cd01e-be55-4922-aca6-70b54d53bb10) | ![Pinned](https://github.com/tachiyomiorg/tachiyomi/assets/46049558/db64105e-fa93-4dfa-a3a9-542df76b044a) | …
=> Add filters to Global search

app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadQueueScreenModel.kt, app/src/main/res/menu/download_single.xml, i18n/src/main/res/values/strings.xml
Issue: https://github.com/tachiyomiorg/tachiyomi/issues/9816
This PR adds an option for user to move series to bottom in the download queue page. I've added text for English only since I'm assuming the translation for other languages will be done with Weblate because of the conversation in this PR: https://github.com/tachiyomiorg/tachiyomi/pull/6794
=> [Download Queue] Move series to bottom

app/src/main/java/eu/kanade/presentation/category/CategoryScreen.kt, app/src/main/java/eu/kanade/presentation/category/components/CategoryDialogs.kt, app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryScreenModel.kt, domain/src/main/java/tachiyomi/domain/category/interactor/ReorderCategory.kt, i18n/src/main/res/values/strings.xml
I reused an existing layout to do this
- I think we should change the sentence of the pop-up  
Closes #6459
| Before | After|
| ------- | ------- |
| ![Screenshot_20230418_192614_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/87093166/233211786-d11658a8-5ad1-483e-bade-c03bf6c138fb.jpg) | ![Screenshot_20230420_000703_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/87093166/233212226-11300104-3830-4ea6-acf5-6127fd79ddc2.jpg) 
|     | ![Screenshot_20230420_000707_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/87093166/233212359-c9357f02-da89-4bdf-9e47-c49306be12ef.jpg)
=> Add button to reorder categories alphabetically

app/src/main/java/eu/kanade/domain/DomainModule.kt, app/src/main/java/eu/kanade/tachiyomi/ui/deeplink/DeepLinkScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/deeplink/DeepLinkScreenModel.kt, domain/src/main/java/tachiyomi/domain/chapter/interactor/GetChapterByUrlAndMangaId.kt, domain/src/main/java/tachiyomi/domain/manga/interactor/GetMangaByUrlAndSourceId.kt, source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/online/HttpSource.kt, source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/online/ResolvableSource.kt
Added functions to ResolvableSource to cater for getting chapters via links 
Automatically load MangaScreen and ReaderActivity from links
Attached is the issue link
https://github.com/tachiyomiorg/tachiyomi/issues/9188
https://github.com/tachiyomiorg/tachiyomi/assets/63104739/54f071a6-a3ba-47c1-afbe-44e2b8577391
=> Allow extensions to open manga or chapter by URL

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt
fix #3052
I think the problem come from scaling, where the layout height is updated. However, when double-clicking, the layout height wasn't reset to original height.
=> fix Can't scroll down to the bottom of the webtoon on the last chapter

app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/MangaRestorer.kt
By wrapping the restoration steps within a single database transaction, we've achieved a considerable reduction in the overall time required to restore large dataset of manga entries into both fresh and non-fresh databases.
- Wrapped the entire `restoreManga` function within a transaction block using `handler.await(inTransaction = true)`.
- Fresh DB restores have shown a 57.31% speed increase, reducing the time from 14 minutes to approximately 6 minutes.
- Non-fresh DB restores have shown an even more impressive 62.57% speed increase, slashing the time from 27 minutes to around 10 minutes.
- The optimization was tested on a dataset containing approximately 3,053 manga entries, each with a varying number of chapters.
edit: added images.
=> Use transaction on restore to go brr.
